### ISSUE TITLE
function documentation not showing

### ISSUE THREAD

**Issue by cknight** [denoland/deno_website2#1036]
Documentation for Deno functions, such as `atob`, `btoa`, `clearInterval`, etc. as defined in https://github.com/denoland/deno/releases/latest/download/lib.deno.d.ts are not showing in deno.land's [runtime API](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts)

**Comment by lucacasonato** [comment]
Wrong repo, and they are working for me: https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#btoa

**Comment by cknight** [comment]
Thanks @lucacasonato, the function is there, but not the javadoc.  Looks like the problem is with `deno doc`.  I'll close here and re-raise in the correct repo.
