### ISSUE TITLE
Url encoded # in /x/ paths is not handled correctly

### ISSUE THREAD

**Issue by littletof** [denoland/deno_website2#1047]
If you visit this url: https://deno.land/x/oak/%23You-Can-Write-anything-here it loads in the repo and display the string after the `%23` in some places, where it shouldnt:
![image](https://user-images.githubusercontent.com/32012862/83903142-eb516a80-a75d-11ea-9383-b37ef2b2629d.png)

It should work like when using a simple `#` ( or show `404` like when it can't find the repo/file )

**Comment by rjoydip** [comment]
The problem is with `%23` if it's `#` is won't show `404` but it won't change like or wont's redirect.

**Comment by littletof** [comment]
@rjoydip If you visit this repo: https://deno.land/x/view_engine and click on the 🔝 emoji in the readme, then this problem will come up. On the github page it navigates correctly with `#`, but on denoland it replaces `#` with `%23`
