### ISSUE TITLE
Third party modules order

### ISSUE THREAD

**Issue by bander-saeed94** [denoland/deno_website2#1050]
I have noticed the alphabet order serves no purpose.

I suggest the order to be based on repo popularity. Or to be in categories (ex: web development, database, cli etc...).

For example the number of GitHub stars.

**Comment by crowlKats** [comment]
popularity is not feasible to do, due to the github api limit

**Comment by lucacasonato** [comment]
Currently yes. Once we have metrics based on downloads counts (which is planned) we can do this.

**Comment by oubenruing** [comment]
Is it feasible to use github actions to call the github API to get the numbaer of stars and update to database.json? 
[Scheduled events: schedule](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
“Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.”

**Comment by lucacasonato** [comment]
No, because this would still have the same rate limit issues as described in https://github.com/denoland/deno_website2/issues/461#issuecomment-629640278

**Comment by TheWizardBear** [comment]
I don't know how feasible this would be but I think the ability to sort by multiple different metrics would be nice. E.g. alphabetical, number of downloads, last updated, Github issues/stars/PRs/watches (I know you ae saying the last one won't be possible but I think it's worth mentioning).

**Comment by ry** [comment]
This was fixed in https://github.com/denoland/deno_website2/pull/1403. Read more about it at https://deno.land/posts/registry2
