### ISSUE TITLE
/index.html doesn't work

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/deno_website2#1060]
![image](https://user-images.githubusercontent.com/28331609/83944084-6f295680-a833-11ea-84d7-da7369f33411.png)

**Comment by lucacasonato** [comment]
Use `https://deno.land/` instead of `https://deno.land/index.html`.

**Comment by nayeemrmn** [comment]
Yeah it's not like it's strongly conventional to support `/index.html` nowadays if ever. Examples: https://github.com/index.html, https://discord.com/index.html, https://www.youtube.com/index.html. This can be closed.
