### ISSUE TITLE
It is recommended to disable CDN acceleration for deno.land.

### ISSUE THREAD

**Issue by 2234839** [denoland/deno_website2#1093]
I'm on a network that's reporting a 403 Forbidden error, which seems to be due to a deno. land is using a restriction imposed by the cdn accelerator, which has to do a human check...

```bash
> deno run https://deno.land/std/examples/curl.ts https://example.com
Download https://deno.land/std/examples/curl.ts
error: Import 'https://deno.land/std/examples/curl.ts' failed: 403 Forbidden
```

**Comment by lucacasonato** [comment]
We use Cloudflare as a CDN for modules. If you have an issue reaching Cloudflare servers, or if they are mistakenly marking your requests as invalid, you should contact Cloudflare support.

**Comment by 2234839** [comment]
> 
> 
> We use Cloudflare as a CDN for modules. If you have an issue reaching Cloudflare servers, or if they are mistakenly marking your requests as invalid, you should contact Cloudflare support.
> 
> If I may ask, which geographical region are you based in?

I am in Zhejiang, China and I will try to contact Cloudflare, but there are many people who have the same problem as me!

**Comment by 2234839** [comment]
@lucacasonato 

Cloudflare responded to me as follows : https://community.cloudflare.com/t/cloudflare-is-preventing-me-from-using-deno-land-properly/181539

    That is probably not the best choice on their side, as Cloudflare is mostly intended for interactive services and not automated scripting, where you can run into exactly such issues.

    That is something they need to address (e.g. adjust their security level) and there is not much Cloudflare can do I am afraid.

**Comment by lucacasonato** [comment]
@2234839 Can you try again? The security level is now less strict.

**Comment by 2234839** [comment]
I'm able to download the code normally, thank you very much for the changes!

**Comment by kotx** [comment]
I am not sure if this is related, but going to any link like https://deno.land/std/examples/curl.ts sends me to https://www.cloudflare-terms-of-service-abuse.com/streaming.ts. Is this because I'm using a browser?

**Comment by lucacasonato** [comment]
No what you are experiencing is denoland/deno_website2#1684.
