### ISSUE TITLE
module's default branch different than master

### ISSUE THREAD

**Issue by oganexon** [denoland/deno_website2#1095]
> If you leave out the branch, it will default to the module’s default branch, usually `master`.

This is the case when importing a module but not on x/
_Edit : importing module also doesn't work when `master` doesn't exist_. 

For example, on my github my main branch is `latest` and there is no `master` branch.
The site should take the main branch and not `master`.

https://deno.land/x/remove_forever@v1.0.0 works
https://deno.land/x/remove_forever don't 

Edit : I created the master branch so my example isn't relevant anymore but the issue is still there

**Comment by lucacasonato** [comment]
Use the default_version option in database.json to choose which branch the module should default to.

**Comment by oganexon** [comment]
I'm gonna stay in the master branch , so it's just cosmetics.
