### ISSUE TITLE
Visiting http doesn't redirect to https

### ISSUE THREAD

**Issue by fletcher-greg** [denoland/deno_website2#111]
Not sure if this is the right place for this, but here goes.

First time visit to deno.land (*no prior visits*) serves up the **http** version rather than **https**.  Not sure if I'm missing something but I assume redirecting to https is preferable. 

To repeat this behavior, cookies should be cleared (obviously) and visit http version or just type deno.land

Just thought I'd let you know. 

Watching the project with interest.

**Comment by rsp** [comment]
Good catch.

http://deno.land/ doesn't redirect to https and it also seems that neither do code URLs:

```
$ curl -i http://deno.land/x/dirname/mod.ts
```
(no redirect, just sending code over unencrypted HTTP)

**But** it has a [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) header:
```
$ curl -i http://deno.land/x/dirname/mod.ts | grep Strict
Strict-Transport-Security: max-age=31536000
```
which is remembered by the browser and tells the browser to never access this website over HTTP. So from now on all HTTP requests to this domain are internally redirected by the browser to HTTPS and so in fact the HTTP request is not going out to the network but only HTTPS (unlike a normal redirect when the browser makes a request, the server gets it and sends a response with a `Location` header and a redirect status code).

I don't know if this is a desired behavior to support user agents that don't understand HTTPS, or is it just a oversight.

**Comment by ry** [comment]
Fixed
