### ISSUE TITLE
Do not assume `master` is the main branch in GitHub

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_website2#1130]
I moved oak's main branch from `master` to `main` and now but the website redirects `https://deno.land/x/oak/mod.ts` to `https://github.com/oakserver/oak/blob/master/mod.ts` instead of `https://github.com/oakserver/oak/blob/main/mod.ts`.

**Comment by lucacasonato** [comment]
Already possible with `default_version` option in `database.json`. I think the best plan forward is going to be to remove the defaulting behaviour and force the user to specify a default branch. This should be ready in a couple of minutes.
