### ISSUE TITLE
Include example in Getting Started for how to run the 'more complex' example

### ISSUE THREAD

**Issue by SirJosh3917** [denoland/deno_website2#1142]
With the strictness of where the --allow-net flag can be placed and the lack of description with what `--allow-net=<allow-net>` could possibly allow, providing an example command to run the provided example would be very helpful. Heck, I didn't even realize that I could pass `--allow-net` without requiring a value. without digging into [some small text at the bottom of the documentation on the website](https://deno.land/manual/getting_started/permissions)

**Comment by tokiedokie** [comment]
done in denoland/deno#5426
