### ISSUE TITLE
Add support for word searching

### ISSUE THREAD

**Issue by sandeshdamkondwar** [denoland/deno_website2#1170]
<img width="1920" alt="Screenshot 2020-06-19 at 2 52 26 PM" src="https://user-images.githubusercontent.com/2510560/85117830-17c8b480-b23d-11ea-98b8-0aacb1339ae9.png">
<img width="1920" alt="Screenshot 2020-06-19 at 2 52 12 PM" src="https://user-images.githubusercontent.com/2510560/85117835-18f9e180-b23d-11ea-90ae-61b2804f2310.png">
<img width="1920" alt="Screenshot 2020-06-19 at 2 46 26 PM" src="https://user-images.githubusercontent.com/2510560/85117838-1a2b0e80-b23d-11ea-94f9-f5db6bc5c054.png">
<img width="1920" alt="Screenshot 2020-06-19 at 2 53 07 PM" src="https://user-images.githubusercontent.com/2510560/85117814-113a3d00-b23d-11ea-9e19-997d2e87e00f.png">

**Comment by lucacasonato** [comment]
Implemented in #1171
