### ISSUE TITLE
Deno cannot find the resource file

### ISSUE THREAD

**Issue by suntianchong** [denoland/deno_website2#1182]
import { Application } from "https://deno.land/oak/mods.ts"

Error: error sending request for the url (https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts) : error trying to connect: DNS error: the requested name is valid, but could not find the requested types of data.(OS error 1
1004).

**Comment by rjoydip** [comment]
@suntianchong I think you importing wrong URL. Check below correct one.

Wrong: `import { Application } from "https://deno.land/oak/mods.ts"`
Correct: `import { Application } from "https://deno.land/x/oak/mod.ts"`

**Comment by suntianchong** [comment]
sorry,&nbsp; I'm wrong






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joydip Roy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月20日(星期六) 中午1:56
收件人:&nbsp;"denoland/deno_website2"<deno_website2@noreply.github.com&gt;;
抄送:&nbsp;"孙天崇"<1247679496@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [denoland/deno_website2] Deno cannot find the resource file (#1182)





 
@suntianchong I think you importing wrong URL. Check below correct one.
 
Wrong: import { Application } from "https://deno.land/oak/mods.ts"
 Correct: import { Application } from "https://deno.land/x/oak/mod.ts"
