### ISSUE TITLE
Large tables don't fit on the screen on mobile

### ISSUE THREAD

**Issue by TheWizardBear** [denoland/deno_website2#1185]
For desktop mode, text wraps around, meaning that tables fits snugly on the screen, filling the horizontal space. This looks great normally but is a bit a of a problem on small screens as the table doesn't fit the width so it ends up being cut off.

Here is an example on my phone (Firefox 68, Android 8.1) from https://deno.land/x/maze_generator:

![screenshot deno table bug](https://user-images.githubusercontent.com/42446683/85206310-0fde4280-b319-11ea-80b4-24b74b78c5d3.png)

I think a simple fix would probably be to add a scrollbar if the table doesn't fit on the screen horizontally.

**Comment by lucacasonato** [comment]
That is weird. I remember making sure this works a while ago. I guess not :man_shrugging:.
