### ISSUE TITLE
500 Error for https://deno.land/x/ through e.g. curl

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno_website2#120]
`curl https://deno.land/x/` throws an 500 error from Cloudflare.

This causes [failure of awesome-bot checks for denolib/awesome-deno](https://github.com/denolib/awesome-deno/commit/03d96426fa29aa207cc558250c4be3d2237e2f99/checks?check_suite_id=325851959)

**Comment by zhmushan** [comment]
@kevinkassimo 
`curl -H "accept: html" https://deno.land/x/` works

**Comment by rsp** [comment]
There are more cases with throwing 500, see #117.
