### ISSUE TITLE
Getting rated limited after running a test

### ISSUE THREAD

**Issue by cezarsmpio** [denoland/deno_website2#1204]
I can no longer download or install any dependencies from Deno registry or even access the deno.land website.

I'm creating a library for Deno and I started writing some tests like:

```
import { superdeno } from "https://deno.land/x/superdeno@main/mod.ts";
import { ServerRequest } from "https://deno.land/std/http/server.ts";
import { createServer } from "./mod.ts";

const handlers = {
  "/": (req: ServerRequest) => {
    req.respond({ status: 200 });
  },
};

const app = createServer({ handlers });

superdeno(app).get("/").expect(200);
```

Then I ran:

```
PORT=3000 deno test --allow-env --allow-net test.ts
```

It started downloading the dependencies then I got two different messages:

```
error: Too many open files (os error 24)

429 Too many requests
```

I tried to access the website deno.land but received a message from Cloudflare, something like:

```
You are being rated limited
```

Any idea?

**Comment by kidonng** [comment]
You are welcome to use other GitHub CDN like jsDelivr. `deno.land` uses Cloudflare workers which is not an optimal choice for serving packages.

**Comment by cezarsmpio** [comment]
Let's say I use a dependency from jsDelivr, for example, but this dependency and its dependencies use `deno.land`. 

I could use `superdeno` from this link: https://raw.githubusercontent.com/asos-craigmorten/superdeno/main/mod.ts and if you check, most of its dependencies are coming from `deno.land`. 

I think that's what happened :/

Anyway, thanks @kidonng!

**Comment by ry** [comment]
This was fixed in https://github.com/denoland/deno_website2/pull/1403. Read more about it at https://deno.land/posts/registry2
