### ISSUE TITLE
Can't cache "gh:" modules on Windows

### ISSUE THREAD

**Issue by hazae41** [denoland/deno_website2#1260]
When I try to cache a "gh:" url on Windows, it fails with 
> error: Could not create TypeScript compiler cache location

### Reproduce

    deno cache -r https://deno.land/x/gh:hazae41:denorand/mod.ts

> Download https://deno.land/x/gh:hazae41:denorand/mod.ts
> Download https://deno.land/x/gh:hazae41:denorand/pkg/denorand.js
> Check https://deno.land/x/gh:hazae41:denorand/mod.ts
> error: Could not create TypeScript compiler cache location: "C:\\Users\\*****\\AppData\\Local\\deno\\gen\\https\\deno.land\\x\\gh:hazae41:denorand"

    deno cache -r https://raw.githubusercontent.com/hazae41/denorand/master/mod.ts

> Download https://raw.githubusercontent.com/hazae41/denorand/master/mod.ts
> Download https://raw.githubusercontent.com/hazae41/denorand/master/pkg/denorand.js
> Check https://raw.githubusercontent.com/hazae41/denorand/master/mod.ts

**Comment by asos-craigmorten** [comment]
FYI, as an aside it looks like these style URLs are being deprecated - #1270
