### ISSUE TITLE
example fails when trying to run

### ISSUE THREAD

**Issue by apopiak** [denoland/deno_website2#1323]
When trying to run the example from `https://deno.land/v1#a-web-browser-for-command-line-scripts` deno errors with the following message:
```
$ deno run --allow-net example.js
Check file:///home/alexander/dev/temp/deno-test/example.js
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.50.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.50.0/path/posix.ts:433:18

Found 2 errors.
```

`deno --version`:
```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

The script does work when removing the versioning.
So the following works:
```ts
import { serve } from "https://deno.land/std/http/server.ts";

for await (const req of serve({ port: 8000 })) {
  req.respond({ body: "Hello World\n" });
}
```

**Comment by buttercubz** [comment]
@apopiak try running using `--reload` flag to download the latest version of  std libs

**Comment by apopiak** [comment]
> @apopiak try running using `--reload` flag to download the latest version of std libs

Because the script mentions the version explicitly in the import that should not make a difference. The error happened on first use when dependencies are fetched anyway. (I was trying out deno for the first time.)

**Comment by apopiak** [comment]
This issue is meant as hint to update the instructions on the webpage so it works on first use :smiley:

**Comment by kitsonk** [comment]
Ref denoland/deno#6723 there are changes afoot so that documentation doesn't have to be updated on every release.

**Comment by lucacasonato** [comment]
Examples in the docs now use versioned imports, so this should not occur again.
