### ISSUE TITLE
bug: abnormal markdown preview

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_website2#136]
see [file_server.ts#L78](https://deno.land/std/http/file_server.ts#L78)

**Comment by zhmushan** [comment]
I found the same bug in vscode markdown preview
![image](https://user-images.githubusercontent.com/24505451/70385764-28b18700-19cb-11ea-9115-d9c425114d96.png)

**Comment by brandonkal** [comment]
@zhmushan I see your opened issue on VSCode was incorrectly labeled as a duplicate of an unrelated issue and closed. Have you opened a new issue there?

**Comment by zhmushan** [comment]
It has been fixed in v10 of highlight.js https://github.com/highlightjs/highlight.js/pull/2380

**Comment by lucacasonato** [comment]
@zhmushan Can this still be reproduced, or can this be closed?

**Comment by zhmushan** [comment]
@lucacasonato Thanks for reminding, this has been fixed
