### ISSUE TITLE
Wanted: provide a list of version information

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_website2#138]
related: https://github.com/denolib/setup-deno/issues/11
Using Github API will limit the rate.

**Comment by MarkTiedemann** [comment]
The GitHub API has a rate-limit, but their website does not.

```javascript
async function versions(set = new Set(), after) {
  let res = await fetch("https://github.com/denoland/deno/releases?after=" + after);
  if (!res.ok) return Deno.exit(1);
  let text = await res.text();
  let lines = text.split("\n");
  let ver;
  for (let line of lines) {
    let match = line.match(/denoland\/deno\/releases\/download\/(.*)\/deno_linux_x64\.gz/);
    if (match !== null) {
      ver = match[1];
      if (set.has(ver)) {
        console.log(Array.from(set).join("\n"));
        return Deno.exit(0);
      } else {
        set.add(ver);
      }
    }
  }
  versions(set, ver);
}

versions();
```
```bash
$ deno --allow-net versions.js
v0.27.0
v0.26.0
v0.25.0
v0.24.0
v0.23.0
v0.22.0
v0.21.0
v0.20.0
v0.19.0
v0.18.0
v0.17.0
v0.16.0
v0.15.0
v0.14.0
v0.13.0
v0.12.0
v0.11.0
v0.10.0
v0.9.0
v0.8.0
v0.7.0
v0.6.0
v0.5.0
v0.4.0
v0.3.11
v0.3.10
v0.3.9
v0.3.8
v0.3.7
v0.3.6
v0.3.5
v0.3.4
v0.3.3
v0.3.2
v0.3.1
v0.3.0
v0.2.11
v0.2.10
v0.2.9
v0.2.8
v0.2.7
v0.2.6
v0.2.5
v0.2.4
v0.2.3
v0.2.2
v0.2.1
v0.2.0
v0.1.12
v0.1.11
v0.1.10
v0.1.9
v0.1.8
v0.1.7
v0.1.6
v0.1.5
v0.1.4
v0.1.3
v0.1.2
v0.1.1
v0.1.0
```
This may be a little brittle, but hopefully it's enough for your use-case for now. :)

**Comment by MarkTiedemann** [comment]
Even better: Listing all versions with a single request:

```typescript
async function main() {
  let res = await fetch("https://raw.githubusercontent.com/denoland/deno/master/Releases.md");
  let text = await res.text();
  console.log(
    [...text.matchAll(/### (v\d+\.\d+\.\d+)/g)]
    .map(m => m[1])
    .join("\n")
  );
}

main();
```
This one also returns `v0.0.0`. :)

**Comment by ry** [comment]
It's worth noting that on the website we use the Github API to get directory listings and it's working fine. The reason we don't get rated limited is the API calls are made from the client side, so any rate limitations apply per visitor, not for the whole site. So I think just using AJAX requests to the API is the best way to do this.

**Comment by MarkTiedemann** [comment]
> any rate limitations apply per visitor

The problem is that "per visitor" does not apply to CI environments, such as, GitHub Actions or Travis, or rather any service where you can't decide which server your code is gonna be run on.

The same happened in the CI of our installer, by the way. Don't have a link now, but I remember it failed because it was rate-limited. This is why we're parsing the website to get the latest version: https://github.com/denoland/deno_install/blob/master/install.sh#L24

**Comment by ry** [comment]
Oh sorry, I misunderstood the issue. I thought this was about providing branch information for deno.land/x/ modules like unpkg.org has.

<img width="357" alt="Screen Shot 2019-12-29 at 11 20 49 AM" src="https://user-images.githubusercontent.com/80/71559538-4c497980-2a2d-11ea-85ea-8b08f1ebdde3.png">

**Comment by zhmushan** [comment]
I just wanted a no rate limit api like https://golang.org/dl/?mode=json&include=all

**Comment by MarkTiedemann** [comment]
@zhmushan 

As far as I know, there's no rate-limiting for https://raw.githubusercontent.com. So, to me, this seems like a good temporary work-around until a Release API is provided.

```typescript
async function getReleases(): Promise<string[]> {
	let res = await fetch("https://raw.githubusercontent.com/denoland/deno/master/Releases.md");
	if (!res.ok) throw new Error(res.statusText);
	let text = await res.text();
	let matches = text.matchAll(/### (v\d+\.\d+\.\d+)/g);
	let releases = [...matches].map(m => m[1]);
	return releases;
}
```
The code wouldn't be too different either if there was an API.

```typescript
async function getReleases(): Promise<string[]> {
	let res = await fetch("https://deno.land/releases.json");
	if (!res.ok) throw new Error(res.statusText);
	let releases = await res.json();
	return releases;
}
```

Same for Node:

```javascript
const https = require("https");

function getReleases() {
	return new Promise((resolve, reject) => {
		https.get("https://raw.githubusercontent.com/denoland/deno/master/Releases.md", async res => {
			try {
				if (res.statusCode !== 200) throw new Error(res.statusMessage);
				let buf = [];
				for await (let data of res) buf.push(data);
				let text = Buffer.concat(buf).toString();
				let matches = text.matchAll(/### (v\d+\.\d+\.\d+)/g);
				let releases = [...matches].map(m => m[1]);
				resolve(releases);
			} catch (err) {
				reject(err);
			}
		}).on("error", reject);
	});
}
```
```javascript
function getReleases() {
	return new Promise((resolve, reject) => {
		https.get("https://deno.land/releases.json", async res => {
			try {
				if (res.statusCode !== 200) throw new Error(res.statusMessage);
				let buf = [];
				for await (let data of res) buf.push(data);
				let text = Buffer.concat(buf).toString();
				let releases = JSON.parse(text);
				resolve(releases);
			} catch (err) {
				reject(err);
			}
		}).on("error", reject);
	});
}
```

**Comment by zhmushan** [comment]
@MarkTiedemann Looks good, thank you!

**Comment by MarkTiedemann** [comment]
Happy to help. :) PS: I edited my comment above.

**Comment by brandonkal** [comment]
@MarkTiedemann why not just query the RSS feed https://github.com/denoland/deno/releases.atom
That would be cleaner than trying to parse the markdown file.

**Comment by MarkTiedemann** [comment]
@brandonkal Didn't know about that. That's pretty sweet! Thanks for sharing. :)

**Comment by axetroy** [comment]
@brandonkal 

Nice!

**Comment by shian15810** [comment]
@brandonkal Fetching from https://github.com/denoland/deno/releases.atom won't provide information about `prerelease` and `draft`.

**Comment by lucacasonato** [comment]
You can get version info from `https://cdn.deno.land/MODULENAME/meta/versions.json` now. It lists all released versions, and the latest.

**Comment by MarkTiedemann** [comment]
@lucacasonato This issue is not about the version of a module, but about Deno's version.

This is similar to https://github.com/denoland/deno_install/issues/115.

**Comment by lucacasonato** [comment]
> @lucacasonato This issue is not about the version of a module, but about Deno's version.

https://cdn.deno.land/deno/meta/versions.json

**Comment by MarkTiedemann** [comment]
> https://cdn.deno.land/deno/meta/versions.json

That's nice.

Unfortunately, I think it's not usable for determining the latest Deno version for downloading the latest Deno binary. That is because there is a time difference between the git tag being pushed and the binaries being built and uploaded. For example, v1.2.2 was tagged at 2020-07-31T19:14:25Z, the GitHub release was created at 2020-07-31T21:06:46Z, almost 2h later, (and the binaries may have been added to the release even later?). That's why, in `deno_install`, we're currently parsing the HTML of the GitHub releases page to figure out the "latest release for the specific platform" - "latest" meaning "binary is available for download".

A quick and dirty solution would be something like this: https://gist.github.com/MarkTiedemann/6ec5dc6b4f968296fa7e7b578ca91ad6 A better solution would need to be integrated into the release process.

**Comment by lucacasonato** [comment]
The versions.json file in this repo contains a list of Deno CLI versions. It is updated manually after artifacts are published.

**Comment by MarkTiedemann** [comment]
Sweet, that's perfect! Thanks. :)

**Comment by MarkTiedemann** [comment]
> @lucacasonato Where can I find the source code / docs for the API?

I'd like to add a feature for returning the latest version in plain text. :)

**Comment by lucacasonato** [comment]
@MarkTiedemann You can find the source code at https://github.com/denoland/deno_registry2. The API is not stable though and is likely to change. There is a little documentation at https://github.com/denoland/deno_registry2/blob/main/API.md. If we want to make the API more extensive I think we should spec it out first. I'll open an issue on the repository.
