### ISSUE TITLE
Architecture: Schematic diagram is outdated

### ISSUE THREAD

**Issue by ipriver** [denoland/deno_website2#1393]
There is an outdated architecture [diagram](https://deno.land/manual/contributing/architecture#schematic-diagram) of the deno process.
![image](https://user-images.githubusercontent.com/9049790/89034932-a3585980-d342-11ea-87ae-098cc12509a2.png)
According to [Releases.md](https://github.com/denoland/deno/blob/master/Releases.md) `libdeno` had been refactored and now deno uses [`rusty_v8`](https://github.com/denoland/rusty_v8) for V8's C++ API bindings.
> ### v0.29.0 / 2020.01.09
> - refactor: Replace libdeno with rusty_v8 (#3556, #3601, #3602, #3605, #3611,
>   #3613, #3615)

**Comment by bartlomieju** [comment]
We're aware of this, it's listed to be updated in https://github.com/denoland/deno/issues/6844

**Comment by ipriver** [comment]
Ok, sorry, haven't seen this to be listed in the deno repository. Closing the issue.
