### ISSUE TITLE
Index doesn't exist for versioned URLs

### ISSUE THREAD

**Issue by rsp** [denoland/deno_website2#140]
Files:
- https://deno.land/std/http/server.ts (OK)
- https://deno.land/std@v0.26.0/http/server.ts (OK)

Indexes:
- https://deno.land/std/ (OK)
- https://deno.land/std@v0.26.0/ (NOT FOUND)

(With no trailing slashes it's the same, plus additionally #116 happens.)

**Comment by lucacasonato** [comment]
This only happens on /std btw, not on /x

**Comment by lucacasonato** [comment]
@ry Fixed by #140. Can be closed
