### ISSUE TITLE
Back button issue on deno.land/x?

### ISSUE THREAD

**Issue by hlian** [denoland/deno_website2#1404]
1. Use latest Firefox on latest macOS
2. Go to https://deno.land/posts/registry2
3. Click on https://deno.land/x/oak/mod.ts
4. Get redirected to https://deno.land/x/oak@v6.0.1/mod.ts
5. Click back button
6. See this:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/63533/89204911-ddb13900-d584-11ea-9956-f9e453779dea.png">

Expected:

Clicking the back button takes me to the blog post.

(Love the project!)

**Comment by ry** [comment]
Similarly if you're at deno.land/x and click any module, you can't use back button to return to the list.
