### ISSUE TITLE
std:0.61/fs 403 forbidden

### ISSUE THREAD

**Issue by avalero** [denoland/deno_website2#1406]
I just found this error when building my api. I was working just fine this morning:

```
error: Import 'https://deno.land/std@v0.61.0/fs/exists.ts' failed: 403 Forbidden
```

**Comment by lucacasonato** [comment]
We special cased this before I think. I am going to fix it giving a 403 instead of 404.

**Comment by avalero** [comment]
This is imported from another module I don't know where it's coming from... 

```
error: Import 'https://deno.land/std@v0.61.0/fs/exists.ts' failed: 403 Forbidden
Imported from "https://deno.land/x/plugin_prepare@v0.7.0/deps.ts:1"
```
