### ISSUE TITLE
Challenge: Re-Link and Publish a new version as owner :) 

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno_website2#1407]
Situation: I'm e.g. the owner of the third party module "cities":

![Screen Shot 2020-08-03 at 7 51 55 PM](https://user-images.githubusercontent.com/43786652/89212018-0b1cd780-d5c3-11ea-9576-163944074cd3.png)

when I try to do so (re-link...): 

![Screen Shot 2020-08-03 at 7 54 16 PM](https://user-images.githubusercontent.com/43786652/89212127-3a334900-d5c3-11ea-89ac-625db418ccae.png)

Perhaps I did not get it if there is another way of "(re)linking". I guess this might be interesting for other third party contributors.

Btw: Thank you for all the fancy things you are doing. It is really bringing open source and collaboration to another level.

**Comment by michael-spengler** [comment]
sorry - I just found out I can press "Next" despite the error message "This module name is not available." Trying to complete it right now :)

**Comment by michael-spengler** [comment]
One step further:

![Screen Shot 2020-08-03 at 8 02 33 PM](https://user-images.githubusercontent.com/43786652/89212801-6ac7b280-d5c4-11ea-8f39-0de4813d175a.png)

Next Challenge: Module not visible in third party modules list (perhaps just a synchronization issue):  
![Screen Shot 2020-08-03 at 8 04 32 PM](https://user-images.githubusercontent.com/43786652/89212923-9f3b6e80-d5c4-11ea-93c3-2ceeae68a9bd.png)

**Comment by lucacasonato** [comment]
I can see the module. You mean the description is not visible? The description is whatever description your GitHub repo has.

**Comment by michael-spengler** [comment]
Cool - I got it now :) 

Thank You.

**Comment by maheshkareeya** [comment]
Got it
