### ISSUE TITLE
"Add a module" docs readability on larger screens

### ISSUE THREAD

**Issue by jeroenptrs** [denoland/deno_website2#1408]
The readability of the add a module documentation could use a few tweaks on readability. Right now:
- The "add a module" sidebar drawer only takes up ~450px on a 4k screens
- Additionally the gif on webhooks is quite unreadable on 1440p and higher

**Comment by ebebbington** [comment]
Could we also suggest to wrap the text for the URL step as a part of this issue? It just flows off the screen (see step 5):
![image](https://user-images.githubusercontent.com/47337480/89700541-c5e00900-d926-11ea-8720-e048d3ec67d0.png)

**Comment by yurianxdev** [comment]
I'll take this
