### ISSUE TITLE
Wrong data in directory listing (date_fns)

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#1409]
https://deno.land/x/date_fns@v2.15.0/add
https://github.com/date-fns/date-fns/tree/v2.15.0/src/add

<img width="1050" alt="Screen Shot 2020-08-03 at 2 19 52 PM" src="https://user-images.githubusercontent.com/80/89214238-7307f980-d594-11ea-86b7-ecd34a9547b3.png">

**Comment by lucacasonato** [comment]
It is fine in the raw data, so it is a display issue: https://cdn.deno.land/date_fns/versions/v2.15.0/meta/meta.json
