### ISSUE TITLE
new website feature for retrieving a package breaks any project relying on the default branch.

### ISSUE THREAD

**Issue by aricart** [denoland/deno_website2#1417]
The deno package strategy will definitely be a challenging mechanism. For example, the new changes to the deno.website that allow self-registration of a module is awesome from one perspective. From another, it looks like we lost the ability to specify a default branch if no version is provided (or that functionality is broken). This type of functionality is a requirement for development.

For example, `https://deno.land/x/tweetnacl_deno/src/nacl.ts` doesn't work correctly - as deno website insists on one of the released versions. Unfortunately, none of those are actually consumable by deno, as the import/exports from those releases don't properly put an extension on the files. Master does.

While technically this is a problem with the library for not having a correct release. The version/tag needs to allow any branch in the repos.

The other lesson here, is that if dependent on a 3rd party library - it is likely a great practice to fork it, since the dependency on an URL creates a very weak binding that can be gone as soon as the owner decides to close/wipe the repo.  NPM at least protects consumers by forever archiving a package.

**Comment by lucacasonato** [comment]
> From another, it looks like we lost the ability to specify a default branch if no version is provided (or that functionality is broken).

This functionality was indeed removed. This was done because we store source code on our servers now, rather than just proxying to raw.githubusercontent.com. Because we only store released versions, not all commits we can't provide code versioned by commit (or branch) anymore.

> This type of functionality is a requirement for development.

For development you can make use of raw.githubusercontent.com links: https://raw.githubusercontent.com/dr-useless/tweetnacl-deno/master/src/nacl.ts, or a service like denopkg.com which replicates the old behaviour of deno.land/x.

> The other lesson here, is that if dependent on a 3rd party library - it is likely a great practice to fork it, since the dependency on an URL creates a very weak binding that can be gone as soon as the owner decides to close/wipe the repo. NPM at least protects consumers by forever archiving a package.

This was actually one of the main reasons we rewrote the registry. We now archive all releases persistently with no way for the package author to delete or update it. After publishing a release, we don't touch the GitHub repository.

**Comment by aricart** [comment]
The main handicap is really that no notice of the change to the behavior. Just was a bit surprised that one of my builds was failing. IMHO the new mechanism is better in some ways - for example, it will be difficult to spoof a library, previously any troll could have pushed a PR changing something.

**Comment by lucacasonato** [comment]
> The main handicap is really that no notice of the change to the behavior. Just was a bit surprised that one of my builds was failing. IMHO the new mechanism is better in some ways - for example, it will be difficult to spoof a library, previously any troll could have pushed a PR changing something.

Yeah, good point - a deprecation warning would have been nice, but we didn't have a good way of implementing it. We monitored the release real time to verify that we didn't have some crazy error rate, and rolled back changes that caused an excessive amount of errors. We will reimplement those changes later, after putting them behind a proper deprecation notice. We are now back to about the same level of 404s as before to change, so the breakage was pretty minimal after all.

**Comment by lucacasonato** [comment]
@aricart Is this issue resolved now?

**Comment by aricart** [comment]
Yes, you can close it
