### ISSUE TITLE
Error on file navigation page

### ISSUE THREAD

**Issue by kidonng** [denoland/deno_website2#1420]
Steps to reproduce:

- Open file navigation page (for example https://deno.land/std or https://deno.land/x/std)
- Browse to a file, let's say https://deno.land/std@0.63.0/README.md
- Go to a folder (by clicking the breadcrumb or browser back button)
- Click any folder or file
- Page went blank with "An unexpected error has occurred." message (if you are on `yarn dev` there won't be any message)

Error message in the console:

![image](https://user-images.githubusercontent.com/44045911/89250786-11a16280-d648-11ea-815e-56f6b2fd9c7b.png)

**Comment by lucacasonato** [comment]
Fixed in #1424
