### ISSUE TITLE
How do I relink my module?

### ISSUE THREAD

**Issue by hidebike712** [denoland/deno_website2#1422]
I had a module called authlete_deno_fen_oauth_server (https://deno.land/x/authlete_deno_fen_oauth_server) as a 3rd party module on deno.land/x, which didn't have any version tags.

When I accessed https://deno.land/x/authlete_deno_fen_oauth_server, I got the following error.

> No uploaded versions
> This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. If you are the owner of this module, please re-link the GitHub repository with deno.land/x, and publish a new version.

So, I've added a version tag to my module but still got the same error. 
Any workaround for this? (I'm wondering how to **re-link the GitHub repository with deno.land/x**).

**Comment by crowlKats** [comment]
you need to follow the instructions from https://deno.land/x#add

**Comment by hidebike712** [comment]
Thank you. 

I'd like to register a module with the same name (= authlete_deno_fen_oauth_server) but the instruction says '**This module name is not available.**' if I input the name as a module name as below, probably because of my existing module... 

![スクリーンショット 2020-08-04 17 11 06](https://user-images.githubusercontent.com/5583716/89271076-2e08c380-d677-11ea-891d-b9afa2f11ab5.png)

Does this mean I need to 

give a new name to my module (e.g. authlete_deno_fen_oauth_server2) on registration 

or 

wait the existing module to be automatically removed from deno.land (as the error says 'Modules that do not upload a version within 30 days of registration will be removed.') and then register the module with the same name again?

**Comment by lucacasonato** [comment]
Just click `Next` even though there is an error message.

**Comment by hidebike712** [comment]
Thanks a lot.

Unfortunately, I still got the "No uploaded versions" error on https://deno.land/x/authlete_deno_fen_oauth_server.

Here's what I did:

1. I've added the module with the same name (= authlete_deno_fen_oauth_server) and set up Github webhook according to the instruction on https://deno.land/x#add.

2. Then, I created a new version tag on my repo (https://github.com/authlete/deno-fen-oauth-server/settings), which seems to have successfully triggered a webhook as below.

![スクリーンショット 2020-08-04 18 10 51](https://user-images.githubusercontent.com/5583716/89276301-75468280-d67e-11ea-8c85-e3e7308464e9.png)

Also, the `status_url` for the webhook above is https://deno.land/status/5f291f4d000439d3003b7c02, which shows me the module publishing has succeeded as below.

![スクリーンショット 2020-08-04 18 16 36](https://user-images.githubusercontent.com/5583716/89276491-afb01f80-d67e-11ea-8a2f-5dd405d7655d.png)

But I still got the "No uploaded versions" error on https://deno.land/x/authlete_deno_fen_oauth_server...

Any suggestions would be appreciated.

**Comment by lucacasonato** [comment]
@hidebike712 It has been uploaded, I can see it. It is probably still caching the old page on your machine. You can refresh with Ctrl+Shift+R to trigger a force reload.

**Comment by hidebike712** [comment]
@lucacasonato Thanks a lot! I can see it now! What an embarrassing mistake...
