### ISSUE TITLE
Possible ePrivacy breach?

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_website2#1429]
From my understanding, since deno.land uses Cloudflare, and the `_cfduid` cookie is set, there should be a cookie banner as stated in the [cloudflare support page for cookies](https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies#12345679).
> Cloudflare encourages our Customers to disclose the use of these cookies to their End-Users (as defined in our Privacy Policy), and in some jurisdictions, Customers may be required to disclose these cookies to End Users.

**Comment by ry** [comment]
Ideally we could disable that cookie ?

**Comment by kitsonk** [comment]
[From their support pages](https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies#12345682:

> The _cfduid cookie can only be disabled for Enterprise customers.
>
> Enterprise customers may request to disable the _cfduid cookie by contacting Cloudflare Support, but Cloudflare’s ability to detect and mitigate the impact of malicious visitors to a Customer’s website will be significantly impacted. While some speed recommendations suggest eliminating cookies for static resources, the performance implications are minimal.
