### ISSUE TITLE
My module description is empty on deno.land/x/

### ISSUE THREAD

**Issue by AkifumiSato** [denoland/deno_website2#1431]
My module name is `dexr`.
It Was visible until just recently.
What should i do?

https://deno.land/x/

**Comment by narwy** [comment]
Do a hard refresh and clear your cache, it's showing for me.

**Comment by lucacasonato** [comment]
The module description on deno.land/x is based on the description on your GitHub repository. To update it on deno.land/x:

1. Update the description on your GitHub repository
2. Create a new tag for your module

@narwy He is talking about the module description displayed in the module list, not the module itself.

**Comment by AkifumiSato** [comment]
@lucacasonato Thanks!
I tried setting the webhook and updating the tags and waited for a day,
but it seems that the explanation does not appear yet.

Is there any other cause?

**Comment by lucacasonato** [comment]
It uses the description of your repository on GitHub. [How to change it](https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github).

After updating the description, you need to release a new tag.

**Comment by AkifumiSato** [comment]
I misunderstood the meaning of the `description` in the repository.
Completed successfully,
Thanks!
