### ISSUE TITLE
Webhook issues with already existing module

### ISSUE THREAD

**Issue by JWebCoder** [denoland/deno_website2#1436]
I've just updated one of my modules **mith** with the new Webhook for /x/ but when I create a new tag I'm getting this error on the webhook: `{"success":false,"error":"module name is registered to a different repository"}`

Can someone help with this?
Thank you.

**Comment by lucacasonato** [comment]
What is the module name?

**Comment by JWebCoder** [comment]
Its mith

**Comment by lucacasonato** [comment]
It is registered to `jwebcoder/mith`. I have changed the repository to `JWebCoder/mith`. Please try to redeliver the webhook from GitHub's UI and see if that fixed it.

**Comment by JWebCoder** [comment]
Can you do the change all modules from jwebcoder to JWebCoder?

**Comment by lucacasonato** [comment]
if you give me the names of all modules, sure

**Comment by JWebCoder** [comment]
mith_static and mith_router at least :)

**Comment by lucacasonato** [comment]
Done

**Comment by lucacasonato** [comment]
This will be closed by https://github.com/denoland/deno_registry2/pull/52

**Comment by JWebCoder** [comment]
Perfect, thank you.
