### ISSUE TITLE
Question: How to update tags of old modules?

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#1441]
Before [the update](https://deno.land/posts/registry2), I have registered quite a few libraries (`args`, `once`, `compose`, etc.). Now, I need to update it but the Web Hook only works on new names.

**Comment by lucacasonato** [comment]
How many modules do you need, and for which repository? I'll increase your limit.

**Comment by KSXGitHub** [comment]
@lucacasonato It worked! Thanks.
