### ISSUE TITLE
New Third Party Module Creation Process is great --> Only Challenge: Owner Transferring Ownership to another Org

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno_website2#1443]
Hi Deno Team.

I think your new "Add Third Party Module Process" is great. 

The only open question I currently have on this is: 
**How do you handle it if an owner transfers the ownership of a connected repository to another org?** 

I guess he will have to delete and re-add the webhook from his new org/repo  - I tested this and got a 400 {"success":false,"error":"module name is registered to a different repository"} 

I'm also still thinking about what the ideal process for the "change org of connected" repo would be - I do not yet have a concrete solution proposal yet.

Kind regards 
Michael

**Comment by lucacasonato** [comment]
Hi,

If you let me know what module to move to what org, I can move the module in the internal database. Ultimately this will be done automatically when we implement https://github.com/denoland/deno_registry2/issues/24.

**Comment by michael-spengler** [comment]
Hi @lucacasonato. 

Thank you for the speedy answer. Here we go: 

https://deno.land/x/learn

New Org/Repo: https://github.com/fancy-flashcard/learn

**Comment by lucacasonato** [comment]
Updated. Just redeliver the GitHub Webhook.

**Comment by michael-spengler** [comment]
Cool. Thank you Luca. It works. --> I close this issue.
