### ISSUE TITLE
Can I use those codes under the MIT license?

### ISSUE THREAD

**Issue by tokiedokie** [denoland/deno_website2#1451]
I am building deno website for Japanese
I don't find any licenses for this repository (except deno image)
Can I use those codes under the MIT license?

**Comment by lucacasonato** [comment]
There is a header on all files specifying that the code is MIT licensed so feel free to fork / copy or do whatever you want with it. The licences for all of the artwork can be found at https://deno.land/artwork.

@ry We seem to be missing a LICENCE file in this repo.

**Comment by ry** [comment]
@tokiedokie This code is MIT, you may use it for a Japanese language website.  I will add a LICENSE file to the project.

**Comment by tokiedokie** [comment]
@lucacasonato @ry Thank you
