### ISSUE TITLE
Part of the sample code is missing on the frontpage

### ISSUE THREAD

**Issue by vladkorotnev** [denoland/deno_website2#1491]
Hi there

Just wanted to let you know that for some reason a part of the "more complex" sample code is missing the package identifier (apparently) and looks like the following:

![image](https://user-images.githubusercontent.com/656194/91511169-0e815580-e91a-11ea-83de-e7a8b557ab11.png)

The "email protected" part points to a file in `/cdn-cgi/`, so I assume Cloudflare or another CDN is misrecognizing the package URL as an email and removing it from the code, essentially rendering it unusable.

**Comment by lucacasonato** [comment]
Thanks - seems incorrect indeed. I have disabled this Cloudflare feature.
