### ISSUE TITLE
deno.lang unaware of new version of third party module

### ISSUE THREAD

**Issue by srackham** [denoland/deno_website2#1499]
I published a new tagged version v1.3.0 to Github but deno.land is unaware of the new version.
16 hours later it's not showing on deno.land:

- https://deno.land/x/drake@v1.3.0  ERROR: 404 - Not found: 
- https://github.com/srackham/drake/tree/v1.3.0/ OK
- https://github.com/srackham/drake/blob/v1.3.0/mod.ts OK

The previous latest version was and still is OK:

- https://deno.land/x/drake@v1.2.6 OK
- https://github.com/srackham/drake/tree/v1.2.6/ OK
- https://github.com/srackham/drake/blob/v1.2.6/mod.ts OK

**Comment by lucacasonato** [comment]
@srackham Did you add the webhook after the recent changes to the registry? See https://deno.land/posts/registry2

**Comment by srackham** [comment]
No I didn't. I've just set up the webhook in my repo and now I can see that one webhook delivery has been successfully made to https://api.deno.land

Thanks for answering so quickly.

I'm guessing that I now need to publish a new release to Github to trigger a release update on deno.land?

**Comment by lucacasonato** [comment]
Yup, exactly

**Comment by srackham** [comment]
Thanks, all sorted.
