### ISSUE TITLE
Incorrect example of "Changes in deno.land/std" inside Deno 1.4 Release Notes

### ISSUE THREAD

**Issue by lcspn** [denoland/deno_website2#1514]
Inside the of the["Changes in deno.land/std" section from Deno 1.4 Release Notes page](https://deno.land/posts/v1.4#changes-in-denolandstd) the second diff is incorrect.

```ts
- const accounting = writeJsonSync("accounting.json");
+ const accounting = JSON.parse(Deno.readTextFileSync("accounting.json"));
```

should be

```ts
- const accounting = readJsonSync("accounting.json"); # Note the writeJsonSync -> readJsonSync change
+ const accounting = JSON.parse(Deno.readTextFileSync("accounting.json"));
```

**Comment by tokiedokie** [comment]
@lcspn You can submit PR to https://github.com/denoland/deno_website2/blob/master/public/posts/v1.4.md

**Comment by tokiedokie** [comment]
FYI, you can edit with "Edit on GitHub" button
<img width="571" alt="edit_on_github" src="https://user-images.githubusercontent.com/42903136/93537111-9bea1f80-f985-11ea-8d7f-f2885e491c41.png">

**Comment by hst-m** [comment]
https://github.com/denoland/deno_website2/pull/1525
