### ISSUE TITLE
Some trash modules need to be removed

### ISSUE THREAD

**Issue by LitoMore** [denoland/deno_website2#1515]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/8186898/93599687-1bf99f00-f9f1-11ea-9af7-7b2d2bad58f8.png">

I got some trash modules when I trying search `react` on The Party Modules page. https://deno.land/x?query=react

Could you remove these trash modules?

BTW, do you have any solution to prevent more trash landing on Deno?

**Comment by lucacasonato** [comment]
This has been resolved.
