### ISSUE TITLE
Import 'https://deno.land/std@master/examples/welcome.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by Hardik500** [denoland/deno_website2#1531]
## Issue
Running the programs in the master version from the manual will return a 404 Error

## Steps to reproduce the issue:
1. Go to [https://deno.land/manual](https://deno.land/manual)
2. Select the version as master from the dropdown
3. Click on "2.3 First steps" from the left dropdown or any other section which has a program link with the version
4. Now run any program, let's say `deno run https://deno.land/std@master/examples/welcome.ts` in the terminal
5. We get the following error:
```
Download https://deno.land/std@master/examples/welcome.ts
error: Import 'https://deno.land/std@master/examples/welcome.ts' failed: 404 Not Found
```

## Steps to fix the issue
1. Try removing @master from `deno run https://deno.land/std@master/examples/welcome.ts`
2. Now the code will run the proper output i.e.
```
Welcome to Deno 🦕
```

3. In my opinion we need a specific condition for @master in the dropdown so that it doesn't get added in the URL

I would like to work on this issue if you allow me to.

**Comment by Hardik500** [comment]
@ry My current solution is adding `code = code.replaceAll("/std@master/","/std/");` in the CodeBlock.tsx file just at the start of RawCodeBlock component. So could you tell me if there is a better place for this code or am I missing something?

**Comment by lucacasonato** [comment]
Easier to just set std version to the latest, instead of master.

**Comment by Hardik500** [comment]
So I changed the code in Manual.tsx file from 
```
<option key="master" value="master">
    master
</option>
```

to 

```
<option key={versions[0]} value={versions[0]}>
    master
</option>
```

Is this the change that you were implying @lucacasonato ?

**Comment by Hardik500** [comment]
This issue is no longer relevant, as the docs have been updated a lot since it was created.
