### ISSUE TITLE
Third party module search is too basic

### ISSUE THREAD

**Issue by cknight** [denoland/deno_website2#1571]
It would be great to have a more powerful search engine in the Third Party module area, perhaps one that could also take into account content in the READMEs.  Some examples of current sub-optimal results:
* search for "middleware" and `oak` squeaks in at 20th
* search for "middleware framework" and `oak` rises to 10th
* search for "oak" and `oak` comes 9th (!)
* My module (Optic) is a logger or deno.  Searching for "log" or "logger" does not return it.  You need to search for "logging" specifically instead which makes discoverability an issue.

**Comment by lucacasonato** [comment]
Totally agree. Closing in favor of https://github.com/denoland/deno_registry2/issues/69 though.

**Comment by cknight** [comment]
I even commented on that one :facepalm:
