### ISSUE TITLE
'Circular structure in "getInitialProps" result of page' error after npm install

### ISSUE THREAD

**Issue by littletof** [denoland/deno_website2#1573]
After a recent `npm i` in the repo, when I ran `npm run dev` it always gave me the error:
```text
Error: Circular structure in "getInitialProps" result of page "/x". https://err.sh/vercel/next.js/circular-structure
    at Function.getInlineScriptSource (...\deno_website2\.next\server\pages\_document.js:717:15)
    at NextScript.render (...\deno_website2\.next\server\pages\_document.js:774:28)
    ...
```

I looked around, and found these two issues:
https://github.com/vercel/next.js/issues/17854
https://github.com/developit/nextjs-preact-demo/issues/25

Changing `next` version to `9.5.3` as mentioned in a comment, seems to resolve this problem for me.
Dont know, if thats the solution, to be taken.

**Comment by lucacasonato** [comment]
That sounds good to me. I think this issue will be addressed in a few weeks.
