### ISSUE TITLE
Remove Unused CSS

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/deno_website2#1602]
Looking at [this page](https://deno.land/x/sheetjs@v0.16.8) in the website, I found it had a ton of unused CSS:
![image](https://user-images.githubusercontent.com/66655515/98846503-ea56f000-2403-11eb-816b-c28d4b3c752c.png)
I was also looking at other pages, and those other pages seemed to use even less CSS than the page I showed you. This is relatively simple as you can just put `purgecss` inside the `postcss.config.js` and it should be solved, I haven't used PurgeCSS with NextJS so I don't know if that will just work, or if something else will need to happen. I am also going to try to do this on my own.

**Comment by lucacasonato** [comment]
We already purge. This could only be fixed by per page CSS file.

https://github.com/denoland/deno_website2/blob/master/tailwind.config.js#L31-L38
