### ISSUE TITLE
Add releases page

### ISSUE THREAD

**Issue by soilSpoon** [denoland/deno_website2#1629]
It would be nice if you could add a page like [Node.js Releases](https://nodejs.org/en/about/releases/) to keep track of deno's release schedule.

**Comment by lucacasonato** [comment]
The latest release is on the homepage. Release schedule can be found at https://deno.land/manual/contributing/release_schedule. Deno does not have LTS releases yet, so we don't need an image showing maintenance schedules.

I think all content is already available on the site, so I will close this.
