### ISSUE TITLE
Preload HSTS

### ISSUE THREAD

**Issue by lgarron** [denoland/deno_website2#1656]
https://deno.land is sending an HSTS header indicating that it should be preloaded for HTTPS in browsers:

https://hstspreload.org/?domain=deno.land
<img width="924" alt="Screen Shot 2021-01-30 at 20 02 51" src="https://user-images.githubusercontent.com/248078/106374261-38f69500-6336-11eb-86c9-c0dfe46e7a14.png">

If this is intended, it would be good to submit the form there!

(If this is not intended, I suggest [removing the header](https://support.cloudflare.com/hc/en-us/articles/204183088-Understanding-HSTS-HTTP-Strict-Transport-Security-#h_4p4noGkEt1dLzosJXarp8V) as soon as possible, because anyone can submit the form.)

**Comment by kidonng** [comment]
@lucacasonato This issue should be resolved quickly, as both the submission for adding and removing can take months for most users to receive.

**Comment by lucacasonato** [comment]
We serve without the `preload` attribute in `strict-transport-security` header now.
