### ISSUE TITLE
README file is not always detected

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno_website2#1721]
It seems to me like README files are only detected if they are
- in the repo root,
- in `.github/`, or
- in `docs/`.

However, for projects like grammY that are in their own subfolder in the GitHub repo, no README file is detected, confer https://deno.land/x/grammy

For grammY, the code is in the `deno/` subdirectory in the repository. Is the subdirectory path disregarded for the README detection, or am I doing something wrong?

**Comment by wojpawlik** [comment]
Since you published `/deno/src/`, I suspect x expects README at `/deno/src/`, not `/deno/`.
