### ISSUE TITLE
ES Modules registry endpoint (?js)

### ISSUE THREAD

**Issue by tommywalkie** [denoland/deno_website2#1722]
It looks like there was once a registry feature allowing users to transpile sources to ESM format _on-the-fly_, which landed in https://github.com/denoland/registry/pull/135, using `?js` parameter.

> I've deployed it. It seems to work!
>
> Check it out https://deno.land/std/io/bufio.ts?js

I tried this feature and it still redirects me to the TypeScript module. I also tried `https://cdn.deno.land/std/versions/0.91.0/raw/io/bufio.ts?js` and got the same result.

Has this feature been removed ? If you can bring it back I think it would make it easier for frontend related projects and non-TypeScript users to adopt Deno and its ecosystem.

**Comment by lucacasonato** [comment]
This feature never existed in the new website.

**Comment by tommywalkie** [comment]
@lucacasonato OK. Is it a planned feature though ?

**Comment by kt3k** [comment]
Let's track this in #1728
