### ISSUE TITLE
Code viewer has poor contrast for  token `dom variable`

### ISSUE THREAD

**Issue by Hydrophobefireman** [denoland/deno_website2#1724]
On  https://deno.land/std@0.91.0/_util/os.ts

Line 10:
![image](https://user-images.githubusercontent.com/29981503/112950844-5a1e0b00-9158-11eb-8964-f07c1e9198d3.png)

![image](https://user-images.githubusercontent.com/29981503/112952210-dfee8600-9159-11eb-92e7-f6a467d3706f.png)

**Comment by kt3k** [comment]
What color do you recommend for this token?

**Comment by Hydrophobefireman** [comment]
Chrome devtools suggests alternative colors for poor contrast

It recommended:
`rgb(82 118 136)` (Contrast ratio 4.5)
`rgb(83 117 136)` (Contrast ratio 4.5)
`rgb(61 88 101)` (Contrast ratio 7.5)

Any of these should be sufficient
