### ISSUE TITLE
Proposal: Create `deno_i18n` repository that include Deno localizations 

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_website2#1729]
Currently Translations for `deno` documentation project are currently maintained in separate repositories. I would good to centralize all this repositories into one single repo.

## Advantages

- Easily to maintain
- Faster and More Efficient Collaboration
- Increased Visibility and Improvement

**Comment by adrai** [comment]
fyi: if you’re looking for a cool and modern way to manage your translations, let me know...
[locize](https://locize.com) could probably do a sponsorship.

At the end of [this page](https://locize.com/i18next.html) there are some examples with usage of [18next](https://i18next.com) in combination with React.js or Next.js

PS. i18next works also in Deno 😉

**Comment by getspooky** [comment]
Any feedback about that ?

**Comment by ry** [comment]
We don’t want to spend any effort on maintaining translations. I’m happy to have a link but reviewing PRs for translations will take away from actual work.
