### ISSUE TITLE
Why does Deno treats `video/*` media types as TypeScript?

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#1732]
When reading https://deno.land/manual/typescript/overview#supported-media-types, I see that Deno treats `video/vnd.dlna.mpeg-tts` and `video/mp2t` as TypeScript file. I think that since the server has determined a file as not being a script, Deno should not treat it as a script.

**Comment by lucacasonato** [comment]
Because many webservers set the content-type header to video/mp2t for .ts files.
