### ISSUE TITLE
Typo on blog post (v1.9 release notes)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_website2#1733]
_Sorry if this is in the wrong repo. It's not clear to me where to file issues related to the blog or where to view the source documents which contain its content in order to send a fix PR. **Will someone inform me?**_

At https://deno.com/blog/v1.9#allow-lists-for---allow-env-and---allow-run it states:

> For example `--alow-read=/tmp` grants read permission only to the `./tmp` directory.

The first path is absolute and the second is relative. Instead, it should state one of the following:

- For example `--alow-read=/tmp` grants read permission only to the `/tmp` directory.
- For example `--alow-read=tmp` grants read permission only to the `./tmp` directory.

---

Additionally: The linked scripts in the example code block in that section return `404`s for me:

```
$ deno run --allow-env=DEBUG,LOG https://deno.com/blog/v1.9/env_permissions.ts
$ deno run --allow-run=deno https://deno.com/blog/v1.9/run_permissions.ts
```

- https://deno.com/blog/v1.9/env_permissions.ts
- https://deno.com/blog/v1.9/run_permissions.ts

**Comment by kt3k** [comment]
@jsejcksn Thanks for the reports! Now these are fixed.

**Comment by jsejcksn** [comment]
Hi @kt3k:

Thanks for updating the paths.

There still seem to be two unresolved issues:

1. The script URLs still return `404` errors:
```
% deno run https://deno.com/blog/v1.9/env_permissions.ts
Download https://deno.com/blog/v1.9/env_permissions.ts
error: Import 'https://deno.com/blog/v1.9/env_permissions.ts' failed: 404 Not Found

% deno run https://deno.com/blog/v1.9/run_permissions.ts
Download https://deno.com/blog/v1.9/run_permissions.ts
error: Import 'https://deno.com/blog/v1.9/run_permissions.ts' failed: 404 Not Found
```

2. In regard to my initial question:

> Sorry if this is in the wrong repo. It's not clear to me where to file issues related to the blog or where to view the source documents which contain its content in order to send a fix PR. **Will someone inform me?**

Is this the right place to post blog-related issue reports in the future? Also, how can I send a PR to fix issues in the blog?

**Comment by kt3k** [comment]
For 1. we updated the urls of scripts
- `https://deno.com/blog/v1.9/env_permissions.ts` -> `https://deno.com/v1.9/env_permissions.ts`
- `https://deno.com/blog/v1.9/run_permissions.ts` -> `https://deno.com/v1.9/run_permissions.ts`

Please try these commands.
```sh
deno run --allow-env=DEBUG,LOG https://deno.com/v1.9/env_permissions.ts
deno run --allow-run=deno,echo https://deno.com/v1.9/run_permissions.ts
```

For 2. we're currently maintaining the blog source code in a private repository, and there's no explicit place for getting feedback for it. I'll talk about this with core members. But for the moment, please create issues in this repository.
