### ISSUE TITLE
[new feature] The number of downloads for third party library

### ISSUE THREAD

**Issue by Gumichocopengin8** [denoland/deno_website2#1737]
Hello, Thank you for the great Deno website.
I wanna propose a feature about the number of downloads for third party library. Currently, the number of GitHub star is the only measurement of popularity. I believe that it would be helpful if there are downloads stats like npm or crate.

**Comment by wperron** [comment]
There's an issue opened on the registry repo, it's been on our radar for a while https://github.com/denoland/deno_registry2/issues/57 It'll be done eventually, feel free to propose other solutions in that thread
