### ISSUE TITLE
Platform specific installation section on homepage

### ISSUE THREAD

**Issue by manishprivet** [denoland/deno_website2#1749]
Right now the Installation section on the homepage shows instructions for all the platforms, leading to unnecessary information. This can be reduced by using browser APIs to show instructions according to the platform.

**Comment by kitsonk** [comment]
That assumes that everyone who is reading instructions is installing it on the system they are browsing from.  That is not a good assumption.  There are quite a few people who browse on other platforms, or use anonymization tools to hide their origin system.  This would then require a "click here for other operating system" which overall would only make something arbitrarily complex that should be simple.

Respectfully closing.
