### ISSUE TITLE
525 error

### ISSUE THREAD

**Issue by michailVestnik** [denoland/deno_website2#1750]
Hi! 
Website https://deno.land loads very slowly, and then gives the error 525.
![Снимок экрана от 2021-05-07 09-43-18](https://user-images.githubusercontent.com/75129392/117383158-136fbd80-af1b-11eb-9cf9-5c79cdc30f42.png)

but if I use a VPN and go to the site from Hong Kong - everything works well!

**Comment by kt3k** [comment]
@lucacasonato Do we use https://deno-website2.now.sh as the origin website? Does the above error screen make sense?
