### ISSUE TITLE
deno.land/std website is often throwing `500` errors when retrieving dependencies

### ISSUE THREAD

**Issue by grempe** [denoland/deno_website2#1785]
I have a Github actions script that runs a Deno command every five minutes. The most frequent cause of failure is a `500` error being generated by the web server serving up `https://deno.land/std...`. It would be great if the source of these errors could be determined and the issue fixed. I've seen this error at least 20 times in the last week in script logging (and I'm sure I'm not alone).

It doesn't seem to be for any particular file. And it has also been observed for `https://deno.land/x` dependencies.

```
error: Import 'https://deno.land/std@0.98.0/fs/empty_dir.ts' failed: 500 Internal Server Error
    at https://deno.land/std@0.98.0/fs/mod.ts:2:0
Error: Process completed with exit code 1.
```

Thanks

**Comment by lucacasonato** [comment]
We have put in place a temporary mitigation for the issue. I'll get back to you with more info and a permanent fix once it is ready.

**Comment by lucacasonato** [comment]
This should now be resolved fully. If you encounter any 5xx class errors in the future please re-open the issue! Thanks for the report :-)

**Comment by jjoynson-iw** [comment]
Hi @lucacasonato, We've been regular 500 errors today. Examples include:

```
error: Import 'https://deno.land/std@0.162.0/fs/walk.ts' failed: 500 Internal Server Error
    at https://deno.land/std@0.162.0/fs/expand_glob.ts:11:32
```

```
error: Import 'https://deno.land/std@0.119.0/node/_fs/_fs_chmod.ts' failed: 500 Internal Server Error
    at https://deno.land/std@0.119.0/node/fs.ts:4:34
```

```
error: Import 'https://deno.land/std@0.119.0/node/util.ts' failed: 500 Internal Server Error
    at https://deno.land/std@0.119.0/node/_errors.ts:16:45
```

Retrying often fixes the problem
