### ISSUE TITLE
Update homepage server example to use "Deno.serveHttp" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_website2#1813]
With `Deno.serveHttp()` stabilized (https://github.com/denoland/deno/pull/11544) we need to update the example on the homepage to use this API instead of pulling HTTP server from `deno_std`.

**Comment by bartlomieju** [comment]
Actually this is a low level API, so maybe we want to wait until `deno_std` updates HTTP server

**Comment by kt3k** [comment]
The example in #1814 looks enough high level to me. No details about HTTP protocol. Users can work directly on `Request` and `Response` objects.
