### ISSUE TITLE
"Deno" is written twice above the fold on the main screen

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#1841]
<img width="1440" alt="Screen Shot 2021-09-01 at 8 55 45 AM" src="https://user-images.githubusercontent.com/80/131674883-e4ed6c8d-781c-4833-9316-7f0275b0f709.png">

Maybe remove the "Deno" text in the upper left?

**Comment by Codercise** [comment]
Just added a PR for this one. I removed the text next to the logo and moved the logo closer to the nav items. On mobile I left the deno title text next to the logo because nothing else is visible when the user has popped open the nav menu.
