### ISSUE TITLE
Docs broken for https://deno.land/x/lambda/mod.ts

### ISSUE THREAD

**Issue by hayd** [denoland/deno_website2#186]
Perhaps due to interfaces? Related to #152?

**Comment by zhmushan** [comment]
I think not related.
#152 was broken at `import { WriteError } from "./constant/errors.ts";`

**Comment by hayd** [comment]
Is it expected the doc page would be blank? (That types don't show up.)

https://deno.land/x/lambda/mod.ts?doc

**Comment by ry** [comment]
Ideally not - but the functionality for re-exports is not yet there. But at least it's not crashing anymore : )
