### ISSUE TITLE
Proxy arbitrary repos from deno.land/x/?

### ISSUE THREAD

**Issue by bcomnes** [denoland/deno_website2#188]
Would it make sense to allow the viewing / proxying of any repo from `https://deno.land/x/`?

e.g. something like `https://deno.land/x/gh/USERNAME/MODULE_NAME@BRANCH/SCRIPT.ts` for GitHub.  Or maybe just `https://deno.land/gh/...`.  

Gitlab and others could be supported with alternate reserved prefixes.  Just thinking about the long term editorial and maintenance contract of database.json.  But maybe its perhaps intended as an editorialized / secondary std.  

It seems like maybe the idea behind https://deno.land/x is similar to that of https://godoc.org and/or the go module proxy?

**Comment by ry** [comment]
I think we'll leave that to other hosts like pika.dev. In some ways deno.land/x is just way to bootstrap the HTTP module system. Maintaining database.json isn't much overhead.

(Ideally github would just have nice URLs, https://github.com/ry/foo/master/bar.js)

**Comment by bcomnes** [comment]
Ok cool thanks for the context.  Yes agreed nicer GitHub URL’s would be ideal.  Fingers crossed pika supports an npm free workflow from GitHub in the future.  Right now it looks like it still needs to be published to a registry.

**Comment by bcomnes** [comment]
Or perhaps GitHub’s own registry could support raw imports of assets.
