### ISSUE TITLE
order the data in benchmark menu

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#190]
<img width="945" alt="Screen Shot 2020-01-16 at 3 52 50 PM" src="https://user-images.githubusercontent.com/80/72561967-59ad9300-3878-11ea-8b83-16cac601ffe1.png">

This is difficult to read

**Comment by jmarthernandez** [comment]
I can take this one.  Looks like it needs a `.sort` in `Benchmarks.tsx`.  Is alphabetically cool?

**Comment by jmarthernandez** [comment]
Opened up #200 

I can change the sort to whatever

**Comment by lucacasonato** [comment]
@ry can be closed because #200 was merged
