### ISSUE TITLE
Change to the Registry Page.

### ISSUE THREAD

**Issue by fakoua** [denoland/deno_website2#192]
Hi, 
In the registry page the top menu (Documentation, Repository, Raw) are displayed with BR and takes extra vertical spaces especially in mobile view.

I want to change this menu to inline horizontal view:

Documentation | Repository | Raw

Please let me know if you agree with this minor change to PR.

Thanks
![d01](https://user-images.githubusercontent.com/2089210/72664859-6dd5c980-3a0b-11ea-966a-72255956b91d.png)

@lucacasonato

**Comment by lucacasonato** [comment]
I think it's good. @ry?

**Comment by ry** [comment]
sure lgtm

**Comment by fakoua** [comment]
Committed: 
[commit a80b9f0f9859c6246f58935373e8fbc3db09dd3c](https://github.com/denoland/deno_website2/pull/191/commits/a80b9f0f9859c6246f58935373e8fbc3db09dd3c)

**Comment by fakoua** [comment]
will create new pr
