### ISSUE TITLE
HTML code showing up between markdown.

### ISSUE THREAD

**Issue by sidntrivedi012** [denoland/deno_website2#20]
![Screenshot 2019-10-22 at 2 23 16 PM](https://user-images.githubusercontent.com/31186013/67271117-8bac9480-f4d7-11e9-9f55-648592de8ed8.png)

@ry, The `prettier` HTML code is being shown between markdown. I was also trying to make the toc but its not being rendered properly. Please guide how to solve this. Would like to work on it. Thanks.

This screenshot is from the Manual page.

**Comment by ry** [comment]
this is solved
