### ISSUE TITLE
docs blank for https://deno.land/x/std/http/file_server.ts

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_website2#207]
Go to https://deno.land/x/std/http/file_server.ts?doc

Page is empty, because there are no docstrings in that file. It would be nice if `Documentation` button was hidden if there are no docstrings.

**Comment by lucacasonato** [comment]
Or maybe disabled with a popover that says that the file contains no docstrings?

**Comment by lucacasonato** [comment]
Can be closed because doc.deno.land
