### ISSUE TITLE
Registry packages should only refer to relative URLs or `deno.land/x/`

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_website2#213]
We should vet packages that are part of the registry to make sure that they don't refer to other hosts, outside of `deno.land/x/`.  We have had reports of some packages referring to `denopkg.com`, which is potentially a useful community feature but we should either include that capability (ability to refer easily to repos on GitHub) into `deno.land/x/` for the use such packages, or we expect everything to only leverage other packages on `deno.land/x/`.

**Comment by ry** [comment]
I think it'd be better to treat deno.land/x as a deno-friendly URL shortener and only have restrictions on std.

**Comment by lucacasonato** [comment]
It's not feasible to introduce this as a restriction for deno.land/x. I will implement a dependency tree view for modules though (so people can make the decision themselves), and maybe later down the line we can introduce a search filter for this.

**Comment by kitsonk** [comment]
Fair enough...
