### ISSUE TITLE
[bug] Docs show incorrect function Types

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno_website2#224]
I've noticed the website is listing the return type here as any, which is not accurate.
The function signature is:
```ts
async function go<E extends Error, T extends Fn>(fn: T): Promise<Go<E, T>>
```
https://deno.land/x/lib/go.ts?doc

**Comment by brandonkal** [comment]
If anyone knows why this is the case, I could look at landing a fix. In fact the parsing function would be useful outside of this website.

**Comment by lucacasonato** [comment]
If still valid should be moved to https://github.com/denoland/doc_website
