### ISSUE TITLE
docs broken https://deno.land/std/ hitting github api rate limit

### ISSUE THREAD

**Issue by JohnstonCode** [denoland/deno_website2#241]
![image](https://user-images.githubusercontent.com/10222719/74671763-c54e8d00-51a3-11ea-8a72-0db8e3e2d9af.png)

**Comment by totallymike** [comment]
This just happened to me. What's the fix?

**Comment by JohnstonCode** [comment]
I was working on somethnig else and came back and refreshed and it was working.

**Comment by ry** [comment]
It's from your own API limit. Your browser is the one making the request.
