### ISSUE TITLE
Is anyone working on a redesign? If not, can I do it?

### ISSUE THREAD

**Issue by samuelgozi** [denoland/deno_website2#257]
Hi, I'm a dev and a designer(you can laugh, but I wanna believe I'm good at both),
and from time to time I like to contribute to open source projects, with both. 

I would like to work on a redesign for the homepage, and then possibly move to the rest. Nothing too fancy, just want to give it a little better structure and make it easier on the eye.

And don't worry, no compromises. If you guys don't like it, don't use it. To be honest, I do it for fun, but if it could be of use Ill even enjoy it more.

**Comment by ry** [comment]
Hello - I'm happy to have contributions but full scale redesigns are probably going to be rejected. I'd rather move the website to a better place in small steps. So if you're interested in doing small patches to fix up stuff, that would be welcome, thanks.
