### ISSUE TITLE
Assertion Error on deno.land/x/denofun/

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#274]
**Step 1:** Go to https://deno.land/x/denofun/
**Step 2:** Open DevTools

**Comment by ry** [comment]
Seems to still be an issue? Any idea what's causing this?

**Comment by KSXGitHub** [comment]
This issue is just duplicate of https://github.com/denoland/deno_website2/issues/276 that I created by mistake.

**Comment by KSXGitHub** [comment]
I have discovered the cause of the issue. It is because `"lib"` field in database.json not having trailing slash.

What fix would you prefer:
  * Editing `getEntry` function in `registry_utils.js` to automatically add trailing slash?
  * Or add a rule to `database.json` to force trailing slash?

**Comment by bartlomieju** [comment]
> I have discovered the cause of the issue. It is because `"lib"` field in database.json not having trailing slash.
> 
> What fix would you prefer:
> 
> * Editing `getEntry` function in `registry_utils.js` to automatically add trailing slash?
> * Or add a rule to `database.json` to force trailing slash?

Second one is more explicit 👍

**Comment by KSXGitHub** [comment]
@bartlomieju Choosing the second one means slowing down people from adding new package. I have experienced this when adding `deno-args`: I sorted the keys in wrong order, causing the CI to fail without informing me (via notification). I only discovered failure of CI few days later,
