### ISSUE TITLE
Page is blank when repo contains a symbolic link

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#276]
[denofun](https://github.com/galkowskit/denofun/tree/ee0fc8a912d6368902f1626e60da118a58361152) contains 3 symbolic links, and [deno.land/x/denofun](https://deno.land/x/denofun@ee0fc8a912d6368902f1626e60da118a58361152/) is complete white.

**Comment by ry** [comment]
Ah sorry - I get lost in all these issues - so the assert error is probably caused from the symlink....

**Comment by KSXGitHub** [comment]
This also affect [my recently added package](https://deno.land/x/args/) too. Its repo used to have symlinks, but I removed it right after discovery of this bug, but it's still blank.

**Comment by KSXGitHub** [comment]
Output of `curl https://deno.land/x/denofun/compose.ts`: https://gist.github.com/KSXGitHub/36ee4f7c2887313bb7d5c46612653aae

**Comment by KSXGitHub** [comment]
This is misleading. Closing this.
