### ISSUE TITLE
deno.land/typedoc (without trailing slash) should redirect to deno.land/typedoc/ (with trailing slash)

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#278]
## Why?

Without trailing slash in the URL, links point to the wrong place.

For example:

![recording](https://raw.githubusercontent.com/KSXGitHub/deno-website-issue-278/master/recording.gif)

**Comment by Drunpy** [comment]
Solved by #311

**Comment by lucacasonato** [comment]
@Drunpy This wasn't actually fixed.

**Comment by Drunpy** [comment]
My bad. Thanks.

**Comment by kidonng** [comment]
https://github.com/denoland/deno_website2/blob/c0bff87d6f2e012ca9dcf7d5eab4eeee876f6d90/worker/src/handler.ts#L15-L17

```diff
  if (url.pathname.startsWith("/typedoc")) {
+   if (url.pathname === '/typedoc') {
+     return Response.redirect('https://deno.land/typedoc/', 301)
+   }
    return proxyFile(url, TYPEDOC_REMOTE_URL, request);
  }
```

Does this simple and stupid solution look fine?

**Comment by lucacasonato** [comment]
Typedoc has been removed
