### ISSUE TITLE
Duplicated documentation entry for default export

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_website2#287]
## Steps to reproduce

1. Go to https://deno.land/x/once/index.d.ts?doc (documentation page of https://deno.land/x/once/index.d.ts)

## Expected behavior

The documentation page should show `once` only once, and show `default` as an alias to `once`.

## Actual behavior

The documentation page shows `once` twice without `default`.

![screenshot](https://user-images.githubusercontent.com/11488886/77224052-8b9ee680-6b94-11ea-89db-475470c3ba58.png)

**Comment by lucacasonato** [comment]
Can be closed because doc.deno.land
