### ISSUE TITLE
Example borken

### ISSUE THREAD

**Issue by mathiasrw** [denoland/deno_website2#292]
On the https://deno.land/std/manual.md page is the example 

    deno install --allow-net --allow-read file_server https://deno.land/std/http/file_server.ts

With latest Deno installed you get

```
Found argument '--allow-net' which wasn't expected, or isn't valid in this context

USAGE:
    deno install <exe_name> <cmd>...
```

When you figure out to swap the location of the flags and it builds it starts getting errors. First one:

```
error TS2339: Property 'readdir' does not exist on type 'typeof Deno'.

► https://deno.land/std/http/file_server.ts:9:21

9 const { args, stat, readdir, open, exit } = Deno;
```

Using

```
deno 0.31.0
v8 8.1.108
typescript 3.7.2
```

![image](https://user-images.githubusercontent.com/1063454/77405183-1c530d80-6db3-11ea-9ec5-40f697f64fdf.png)

**Comment by lucacasonato** [comment]
You seem to be using an old Deno version (0.31.0). The latest is 0.37.1.

You can also use the file server locked at version 0.31.0:
```
deno install --allow-net --allow-read file_server https://deno.land/std@0.31.0/http/file_server.ts
```

**Comment by mathiasrw** [comment]
@lucacasonato Thank you for looking into this. 

Hmm. This is strange. I upddates with `curl -fsSL https://deno.land/x/install/install.sh | sh` but still have 0.31.0

Am I meant to install in a different way?

![image](https://user-images.githubusercontent.com/1063454/77513277-fbeb8780-6e74-11ea-886a-74111b1bfd86.png)

**Comment by cknight** [comment]
What is the output of `which deno`?  Also, you can try `/Users/mrw/.local/bin/deno --version`

**Comment by mathiasrw** [comment]
Ohhh - look. It did get installed! Have we changed where its installed? LIke, is this because installation location have changed since I installed it the first time?

![image](https://user-images.githubusercontent.com/1063454/77533408-1b93a780-6e97-11ea-942e-d2854062ae9d.png)

**Comment by ry** [comment]
@mathiasrw probably a homebrew install

**Comment by mathiasrw** [comment]
Thanks. Ill find a way.
