### ISSUE TITLE
issue(deno-debug): demo image not showing

### ISSUE THREAD

**Issue by rjoydip** [denoland/deno_website2#296]
***Issue***
In reame file of `deno-debug` repo. There is a demo image but in deno docs it is not showing.

***Screenshot***
`deno-debug`:

![image](https://user-images.githubusercontent.com/15318294/78232765-5b3f3c80-74f2-11ea-8595-e7c096e5c014.png)

<hr />

`In deno dock`s:

![image](https://user-images.githubusercontent.com/15318294/78232706-45317c00-74f2-11ea-9ec4-46c561d5806d.png)

**Comment by lucacasonato** [comment]
This should be fixed.
