### ISSUE TITLE
Serve type stripped versions of files

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_website2#356]
`https://deno.land/std/http/mod.ts` -> `https://deno.land/std/http/mod.ts?js`

**Comment by mreinstein** [comment]
this would enable the use case of loading modules directly from a browser, which would be phenomenal.

**Comment by ry** [comment]
ideally just
https://deno.land/std/http/mod.ts -> https://deno.land/std/http/mod.js

**Comment by lucacasonato** [comment]
Thought about this, but is relatively difficult because all imports also need to be rewritten from '.ts' to '.js' which is annoying. Serving a bundle at `https://deno.land/std/http/mod.ts?bundle` might be easier as a first pass.

**Comment by lucacasonato** [comment]
This is part of the registry roadmap: https://github.com/denoland/deno_registry2/issues/35
