### ISSUE TITLE
Design mockup

### ISSUE THREAD

**Issue by Droces** [denoland/deno_website2#368]
Hi guys; just came across the project - which I think is super exciting! - and wanted to contribute. As a website designer developer, I thought I could start with a website design revamp.

[Mockup v1 in UXPin](https://preview.uxpin.com/ea6a824f96a4ad5fdc0f4112935ce2921fe0ed70#/pages/128607413/simulate/no-panels?mode=i)

That's as simple as it could be, without any colours / branding, which I think should be added soon.

If you like it and want to provide feedback, feel free to leave comments on the design (using the built-in comment tool) or here as appropriate.

**Comment by ry** [comment]
Thanks for the offer but we have a new design that will be released soon.
