### ISSUE TITLE
Repository README previews not displaying images correctly.

### ISSUE THREAD

**Issue by sunsetkookaburra** [denoland/deno_website2#371]
![image](https://user-images.githubusercontent.com/55334808/81446810-da452600-91be-11ea-8aa8-42ad4c3bd777.png)
![image](https://user-images.githubusercontent.com/55334808/81446830-e16c3400-91be-11ea-88fa-fbb2d227b04e.png)

(opened to track, i'll provide a patch to public/style.css)

**Comment by lucacasonato** [comment]
Fixed by #408
