### ISSUE TITLE
Add darkmode again

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_website2#40]
We should add darkmode again like we had on the v1 site. It should be based on prefers-color-scheme again.

We have to update:
- main layout (material-ui theme)
- code blocks (so cant use github-gist theme anymore)
- charts (once/if #39 is merged the apexcharts theme)
- invert deno logos

**Comment by ry** [comment]
Sure - but let's please keep the CSS as minimal as possible.

**Comment by lucacasonato** [comment]
Fixed by #60.
