### ISSUE TITLE
Merge Luca's new website

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#403]
- [ ] change the REMOTE_URL in worker/src/handler.ts to https://deno-website2.now.sh
- [ ] switch the credentials and domains in worker.toml 
- [ ] change the build settings on Vercel to "Next.js"
- [ ] change `github.repository` in `.github/workflows/ci.yml` to `denoland/deno_website2`

**Comment by lucacasonato** [comment]
Fixed by #408
