### ISSUE TITLE
Update VS Code plugin link on Manual

### ISSUE THREAD

**Issue by fnick851** [denoland/deno_website2#419]
The VS Code plugin listed on this page - https://deno.land/manual/getting_started/setup_your_environment - is already deprecated: https://github.com/axetroy/vscode-deno

I think the official one is this: https://github.com/denoland/vscode_deno/

**Comment by lucacasonato** [comment]
A PR fixing this has been opened on the denoland/deno repo: https://github.com/denoland/deno/pull/5292

**Comment by fnick851** [comment]
@lucacasonato Thanks!
