### ISSUE TITLE
std/log webpage errors out

### ISSUE THREAD

**Issue by cknight** [denoland/deno_website2#426]
Visiting https://deno.land/std/log yields:

> Failed to get directory listing
Unexpected end of JSON input

**Comment by lucacasonato** [comment]
That is interesting.  Can you check if there are any errors logged to the console. Are you behind a firewall that blocks the Github API?

**Comment by cknight** [comment]
https://raw.githubusercontent.com/denoland/deno/master/std/log is returning 404, however I'm seeing this on most other std pages which are loading fine.  The only other error in the console is:

```
8734a37fe83f25a08c43362e0e2405bf8347ad80.e3f9d19a22781935d2af.module.js:1 Failed to fetch dir entry: SyntaxError: Unexpected end of JSON input
```

**Comment by cknight** [comment]
OK, this is browser specific.  If I use Brave, I get the above.  If I switch to Firefox, the page loads as expected.  `https://api.github.com/repos/denoland/deno/contents/std/log?ref=master` is being treated as a cross-site tracker and is being blocked.  Taking Brave's 'sheilds' down resolves the issue.  Interestingly, `std/log` is the only page where the api call is being treated as a cross site tracker.  Bug in Brave?

**Comment by lucacasonato** [comment]
I would say so. Brave probably thinks anything with the word log in it is a logger. 🤷‍♂️

**Comment by cknight** [comment]
Issue logged against Brave:  https://community.brave.com/t/incorrect-cross-site-tracking-block-for-url/126852

**Comment by cknight** [comment]
FYI, now fixed in upstream Brave.
