### ISSUE TITLE
add selectable line numbers

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#43]
Allow selecting lines with URL fragment: http://deno.land/std/http/server.ts#L1-#L5

@j-f1 implemented this already somewhere in https://github.com/denoland/registry/tree/master/src so maybe try to reuse code from there.

**Comment by j-f1** [comment]
https://github.com/denoland/registry/blob/714ffcf29d55620fb02b53c99c7d954a366a19e7/src/code_scripts.js#L12-128
