### ISSUE TITLE
Standard library page error

### ISSUE THREAD

**Issue by xiaohp** [denoland/deno_website2#433]
https://deno.land/std
![image](https://user-images.githubusercontent.com/23056320/81916390-577cfa80-9606-11ea-89d8-752ed1a2cb64.png)
Failed to get directory listing
Querying the GitHub API failed. This is usually caused by a network outage or because you have reached your hourly API rate limit of 60 requests.

**Comment by lucacasonato** [comment]
Yes - this means that you have looked at so many pages that you have depleted your rate limit. This is expected, and we can not do anything about this.

**Comment by kidonng** [comment]
> we can not do anything about this at the moment.

jsDelivr has a [API](https://github.com/jsdelivr/data.jsdelivr.com/blob/master/README.md#list-package-files) for listing package files and seems to be used by Yarn registry.

> The API is free to use and imposes no rate limits. However, if you plan to make 100+ RPM for longer periods of time, you should contact us first.

**Comment by lucacasonato** [comment]
Oh @kidonng that is a good find! I will look into this.

**Comment by kidonng** [comment]
There is a problem regarding jsDelivr, it can only provide file list based on git tags. This doesn't matter to `std` as it is tagged properly, however for 3rd party modules it can cause problems.

**Comment by alirealasad** [comment]
I didn't even seen a single page from this morning but I still getting this error on every module's page. 

at least please add a link to the repo or something so that I can visit the repo if get this error

**Comment by reselbob** [comment]
Help? I am doing a significant, commissioned research project on Deno for a publication. I really would like to be able to review third party modules. But, given what I am reading here there is nothing I can to get access. If I am mistaken, please set me straight.

**Comment by lucacasonato** [comment]
If you are seeing this error you can follow these steps to determine what is causing it. 

1. Have you viewed more than 30 documentation, standard module or third party pages in the last 60 minute?
    - **Yes**: You have reached your personal GitHub API rate limit. There is nothing much you can do right now. Please wait 60 minutes for your rate limit to reset.
    - **No**: Continue to step 2.
2. Can you view the page `https://raw.githubusercontent.com/denoland/deno/master/std/examples/welcome.ts` without error?
    - **Yes**: Continue to step 3.
    - **No**: Some network configuration is causing an issue on your end while trying to reach GitHub. This is most likely because you are in mainland china or behind a corporate VPN that is blocking raw.githubusercontent.com.
3. Disable all ad blockers and content filters and check if the error persists.
    - **Still errors**: Continue to step 4.
    - **No error**: Your ad blocker or content filter is blocking the request to GitHub.
4. Try the page load in a different browser:
     - **Still errors**: Continue to step 5.
    - **No error**: Your browser is blocking the request to GitHub.
5. Please capture an HAR of your page load and reply to it on this issue.

**Comment by reselbob** [comment]
I went in with another browser, in this case, Safari, rather than my usual Chrome. I could access the  Third Party libraries pages.

**Comment by hkong** [comment]
I put in a request to have the Deno API docs added to DevDocs (https://trello.com/c/SUWvkeGy/485-deno).  It would alleviate this particular issue, and also help those who have slow/limited bandwidth.

**Comment by kidonng** [comment]
@hkong Thanks! But the manual page only needs one request to rate-limited `api.github.com`, so people usually don't have problems accessing it. Adding the docs to DevDocs would be great, but it doesn't help with this issue.

**Comment by wayjam** [comment]
It is easy to trigger the limitation in the enterprise network or behind a proxy.

**Comment by kidonng** [comment]
According to https://github.com/denoland/deno_website2/pull/522#issuecomment-660527801 this issue is being worked on so stayed turned.
In the meantime, you can just browse https://github.com/denoland/deno/tree/master/std instead, there's no difference.

**Comment by ry** [comment]
This was fixed in https://github.com/denoland/deno_website2/pull/1403. Read more about it at https://deno.land/posts/registry2.
