### ISSUE TITLE
Deno manual chapters blank

### ISSUE THREAD

**Issue by Marcos-Costa** [denoland/deno_website2#435]
The [7.5. documentation generator](https://deno.land/manual/tools/documentation_generator) and [7.6.Dependency Inspector](https://deno.land/manual/tools/dependency_inspector) chapters in deno manual are currently blank.

**Comment by lucacasonato** [comment]
> The [7.5. documentation generator](https://deno.land/manual/tools/documentation_generator) and [7.6.Dependency Inspector](https://deno.land/manual/tools/dependency_inspector) chapters in deno manual are currently blank.

This is because they are empty - there are actually no docs for these atm. Sorry...

**Comment by cknight** [comment]
@lucacasonato not sure if it's worth it, but on missing/empty docs, could a message be put up instead saying 'No docs currently available' or whatever?
