### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#44]
set it up here https://github.com/denoland/deno_website2/blob/fbe617646c93dfff919d4d70722be82e5527e3f0/.github/workflows/build.yml#L16
and no need to add comprehensive tests, just add an example of how to test react (a good example test would be to check that the home page renders properly and contains the word "Deno")

**Comment by lucacasonato** [comment]
Do we want to emulate the DOM using something like JSDOM for testing or should we use something like [puppeteer](https://github.com/GoogleChrome/puppeteer)? I think maybe JSDOM for unit tests and then a few puppeteer integration tests.

**Comment by ry** [comment]
@lucacasonato I think unit tests with jsdom will be sufficient for starts
