### ISSUE TITLE
Consider adding background-color on `search_field`

### ISSUE THREAD

**Issue by sidvishnoi** [denoland/deno_website2#453]
This is how the search field looks on Firefox on Ubuntu.
![image](https://user-images.githubusercontent.com/8426945/81967278-549afd80-9638-11ea-822c-c9c63341f19e.png)
vs in Chrome:
![image](https://user-images.githubusercontent.com/8426945/81967358-6d0b1800-9638-11ea-9aa2-db763eff6168.png)

~I would've sent a PR, but I don't want to learn Tailwind at this time.~

Trivia: Firefox uses a special color value called `-moz-Field` as input `background-color`, which is based on OS themes, but Chrome has `#ffffff` by default.

**Edit:** Oh wait. It's just `.bg-white` :sweat_smile:

**Comment by kennanseno** [comment]
@bartlomieju can be closed
