### ISSUE TITLE
ux: "active" link indicator in the sidenav for the manual

### ISSUE THREAD

**Issue by KeziahMoselle** [denoland/deno_website2#457]
![A page on the manual](https://i.imgur.com/htY5PGS.png)

Adding a distinction between an active and a normal link in the sidenav would greatly improve the UX

Because i'm often trying to CTRL+F to find where I was in the sidenav, little details you know !

**Comment by kennanseno** [comment]
I can pick this up unless you wanna take it yourself @KeziahMoselle ?

**Comment by KeziahMoselle** [comment]
Feel free to do it @kennanseno !
