### ISSUE TITLE
Search is not working in the Manual

### ISSUE THREAD

**Issue by timharek** [denoland/deno_website2#470]
I'm using latests Firefox 76.0.1, also tried latest Safari and no luck with the search function in the manual; https://deno.land/manual

**Comment by qadratic** [comment]
I doubt there is some code to do that. Its very much work in progress.

**Comment by lucacasonato** [comment]
Yup - it is not implemented atm. We should remove the search field for the moment.

**Comment by qadratic** [comment]
I can actually make it functional but at the moment I am opening a pr to disable it.

**Comment by nayeemrmn** [comment]
@lucacasonato A single page view would be great, so we could <kbd>Ctrl</kbd>+<kbd>F</kbd> and for lots of other reasons. Might not need a built-in search. Would it be very difficult?

**Comment by loilo** [comment]
I think even on a single page, a built-in search would still have benefits, especially when it comes to prioritization of search terms (e.g. higher weighted in headlines than in body text etc.)

**Comment by lucacasonato** [comment]
> @lucacasonato A single page view would be great, so we could Ctrl+F and for lots of other reasons. Might not need a built-in search. Would it be very difficult?

Difficult no, just a lot of fetches to GitHub.

**Comment by nayeemrmn** [comment]
We need a way to publish some set of auto-generated files with every commit on master. This would be used for `lib.deno.d.ts` (which can only be accessed on latest release right now, a crippling inconsistency), `docs/toc.json`, and a pre-concatenated single page manual.

We do this with https://github.com/denoland/benchmark_data...

**Comment by lucacasonato** [comment]
Algolia DocSearch might work for this too: https://docsearch.algolia.com/

**Comment by erlend-sh** [comment]
We’re big fans of Rust and Deno at [MeiliSearch](https://github.com/meilisearch/MeiliSearch) and we’d love to assist with setting up a self-hosted or managed search for you should the need arise.

https://docs.meilisearch.com/resources/howtos/search_bar_for_docs.html

**Comment by lucacasonato** [comment]
Update: we have reached out to Algolia about DocSearch.
