### ISSUE TITLE
Dont use curl | sh for installation

### ISSUE THREAD

**Issue by eoftedal** [denoland/deno_website2#480]
When promoting something as a secure alternative, this will make a lot of people iffy:
https://github.com/denoland/deno_website2/blob/master/pages/index.tsx#L295

Please use better ways of installing it (apt, brew etc.) instead of curl|sh.

**Comment by oplik0** [comment]
If you look just a few lines below it you'll see brew.
Deno isn't yet possible to install via apt - and adding it there isn't an issue with the website. And it does exist in the correct repo: denoland/deno#1583

However, Deno is available on some package managers besides chocolatey/scoop/brew that are mentioned on the website - see [here](https://repology.org/project/deno/versions)

I think AUR and Linuxbrew could be added to denoland/deno_install as two of the additional installation options mentioned on the website.

However, one installation method that is even in the manual but is missing from the website is cargo.  Is there any reason why it's the only option that's in the manual but no on the main page? It's even weirder when you consider that it's the only option that works on **all** major platforms - Windows, macOS and Linux all can use cargo to install deno as long as they have rust installed.

**Comment by lucacasonato** [comment]
More related to denoland/deno_install

**Comment by kidonng** [comment]
The installing scripts are open source and easy to read. I don't see any problem about executing remote scripts if you **know and trust** the source.
That said, anyone having security concerns can simply grab the binary by hand, Deno is made simple for this use case.
