### ISSUE TITLE
consider adding opengraph cover images

### ISSUE THREAD

**Issue by KeziahMoselle** [denoland/deno_website2#488]
When someone links the Deno website the cover image will be easier to scan and will probably be helpful for sharing or references purposes (in personal wikis for examples that embed a cover)

Of course it is a small detail but it can be a great addition ! 😄 

![Current preview](https://i.imgur.com/lynjpjx.png)
[See on https://metatags.io/](https://metatags.io/)

I'm using Notion and when I create a bookmark of Deno it's like this : 
![Notion's bookmark of Deno](https://i.imgur.com/u0w1Sff.png)

Of course it's specific to Notion's behavior, just thought it would be a nice thing to have.

**Comment by mechamobau** [comment]
I want to work on it, the image showed in the card can be the image located on `public/v1_wide.jpg`?
