### ISSUE TITLE
Deno.land serves the wrong raw files ( but the right HTML )

### ISSUE THREAD

**Issue by garronej** [denoland/deno_website2#502]
Hi,  
  
If you visit https://deno.land/std/node/_fs/_fs_readlink.ts ( not specifying the branch ) you will get an HTML page displaying the current version of the file.

However if you ``wget https://deno.land/std/node/_fs/_fs_readlink.ts`` you will get a very old version of the file for some reason...

**Comment by lucacasonato** [comment]
I can not reproduce. What is the difference?

**Comment by garronej** [comment]
Well, the difference was that it didn't serve the version on master.

Anyway, it seems to be working now as I can no longer reproduce.
I close this issue now, I will reopen it re surface. 

Thanks
