### ISSUE TITLE
Link to source markdown files on Github

### ISSUE THREAD

**Issue by buckle2000** [denoland/deno_website2#516]
I think each page in /manual should link to a file in https://github.com/denoland/deno. It will let people to find it more easily.
I don't understand why https://github.com/denoland/deno is not a git submodule.

btw, the `.map` loop syntax in JSX is really terrible.

**Comment by lucacasonato** [comment]
I agree, a footer under each page with a link that says `Edit on GitHub` that links to the correct file on GitHub.
