### ISSUE TITLE
API reference is hard to find - should be linked on top of page

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno_website2#546]
# It's not here:

![image](https://user-images.githubusercontent.com/218257/81892748-28d23600-95ac-11ea-9782-c9b78e39e025.png)

# Not here either:

![image](https://user-images.githubusercontent.com/218257/81892790-47d0c800-95ac-11ea-9533-07a17d1a8ff2.png)

# It must be somewhere. But where...? Oh!

![image](https://user-images.githubusercontent.com/218257/81892911-92524480-95ac-11ea-8440-3eb081683b40.png)

**Comment by kidonng** [comment]
`doc.deno.land` is hard to discover too. (Looks like it's the same problem)
