### ISSUE TITLE
Is there any consensus on using reserved keywords as package name

### ISSUE THREAD

**Issue by searchableguy** [denoland/deno_website2#547]
- enum:
https://github.com/denoland/deno_website2/blob/98a4d631b95740fd2c9ba0cc4276c1cc267dd548/database.json#L642-L647

- case: 
https://github.com/denoland/deno_website2/blob/98a4d631b95740fd2c9ba0cc4276c1cc267dd548/database.json#L129-L134

Both are reserved keywords so imports like import case from "deno-change-case" won't work. But currently, I am using a script to import some of them and I have to deal with them by renaming them.

It also causes confusion - with enum package only intended for js audience since enum already works in typescript.

**Comment by kidonng** [comment]
The current implementation of the registry is rather simple and prone to error. Discussion at #406
