### ISSUE TITLE
images/deno_logo_4.gif looks bad on some apps/browsers

### ISSUE THREAD

**Issue by algiuxass** [denoland/deno_website2#560]
Rain animation looks bad on some browsers/apps (Discord on iPhone and Linux) and may look fine on browsers/apps (Firefox on Linux).

Original:
![deno_logo_4](https://user-images.githubusercontent.com/33424336/82143322-b7b0ae00-984b-11ea-9e0a-cfa5279d616c.gif)

I asked couple of people on Discord to confirm this problem, for some people it animates rain correctly, for some it does not.

![2020-05-17-14-09-58](https://user-images.githubusercontent.com/33424336/82142880-605d0e80-9848-11ea-9b31-86fd7a82bc98.gif)
![20-05-17-15-24-45](https://user-images.githubusercontent.com/33424336/82143341-d8790380-984b-11ea-8a52-aadd7347c666.gif)

**Comment by tokiedokie** [comment]
I don't think this is a problem with this web site, but with discord
