### ISSUE TITLE
Link parsing of README is inconsistent with Github Markdown

### ISSUE THREAD

**Issue by Qu4k** [denoland/deno_website2#562]
### Issue
You can see this issue in the README.md file in the status module ([GitHub](https://github.com/denosaurs/status) vs [Deno](https://deno.land/x/status)). The square brackets in the headings are not followed by a `()` but they are still parsed as links in the Deno markdown rendering. This is not the case in the Github markdown rendering of the same README.

### Possible solution
```typescript
// components/Markdown.tsx
const renderers = (canonicalURL: string) => ({
  // ...
  // adding linkReference in the renderers
  linkReference: LinkRenderer,
  // ...
});
```

```typescript
// components/Markdown.tsx
function LinkRenderer(props: LinkRendererProps) {
  // ...
  // adding a check if the href is actually present
  if (href) {
    return (
      <a href={href} className="link">
        {props.children}
      </a>
    );
  }
  return (<>[{props.children}]</>):
}
```

Should I open a pull request to implement these changes?

**Comment by rjoydip** [comment]
Issue is in `react-markdown`. But it's not in `LinkRenderer` issue. Issue is in `HeadingRenderer`

**Comment by Qu4k** [comment]
> But it's not in LinkRenderer issue. Issue is in HeadingRenderer

My _possible solution_ was a quick fix on the deno website side. I too saw that the problem resides in fact on the `react-markdown` but I figured a maybe it was meant to be a feature. Thanks on opening the issue though :)
