### ISSUE TITLE
Reference to a non-available package keeps loading

### ISSUE THREAD

**Issue by frunkad** [denoland/deno_website2#579]
When referring to a non-std package which does not exist it keeps loading.

Eg: https://deno.land/x/random-package

Whereas doing the same for std package shows a valid error response

Eg: https://deno.land/std/random-package

**Comment by frunkad** [comment]
Can I take this issue, might need a little guidance.

**Comment by kennanseno** [comment]
Will look at this unless someone else wants to take it

**Comment by ry** [comment]
fixed
