### ISSUE TITLE
RSS/Atom support

### ISSUE THREAD

**Issue by silvioprog** [denoland/deno_website2#594]
Please enable RSS/Atom support at the blog/site. It will be useful to get groups/forums (e.g.: in Telegram, using `@rss2tg_bot`) updated regarding new posts.

**Comment by j-f1** [comment]
Bumping this. It would be great to read blog posts in my newsreader instead of having to manually check the blog!

**Comment by satyarohith** [comment]
Atom feed: https://deno.com/feed

**Comment by silvioprog** [comment]
Thank you dudes! 👍
