### ISSUE TITLE
Benchmark charts - bad values for throughput and exec time

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_website2#61]
<img width="974" alt="Zrzut ekranu 2019-10-25 o 13 25 13" src="https://user-images.githubusercontent.com/13602871/67567825-f1448f00-f72a-11e9-8eab-6aed8f93efb8.png">

If you check latest benchmarks (https://github.com/denoland/deno/runs/274208380) you can see that both of those charts should be <2s but all of the results are >4s on charts.

CC @lucacasonato @ry

**Comment by lucacasonato** [comment]
Interesting - seems to happen only after interacting with the normalized toggle. I'll look into this.

**Comment by lucacasonato** [comment]
Seems to be related to the logarithmic scaling of the graphs. I don't quite understand what exactly is causing the undesired behavior - I'll look into this some more.

**Comment by lucacasonato** [comment]
I think this does not happen anymore.

**Comment by bartlomieju** [comment]
I can still reproduce it

**Comment by lucacasonato** [comment]
Fixed by #408
