### ISSUE TITLE
document generator documentation is absent

### ISSUE THREAD

**Issue by therealadityashankar** [denoland/deno_website2#619]
https://deno.land/manual/tools/documentation_generator does not have any documentation on the website
![image](https://user-images.githubusercontent.com/21975892/82360328-d8812b00-9a26-11ea-9eca-c8dd6d4aba63.png)

**Comment by therealadityashankar** [comment]
closing this issue and moving it to denoland/deno

**Comment by nayeemrmn** [comment]
@therealadityashankar It's got a TODO comment in it, won't really be a helpful issue unless you intend on addressing it?
