### ISSUE TITLE
sidebar menu close button working

### ISSUE THREAD

**Issue by rjoydip** [denoland/deno_website2#624]
Deno manual close button not working on small screen.

![localhost_3000_manual(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/15318294/82365155-e7b7a700-9a2d-11ea-9693-197daa2b607b.png)

**Comment by lucacasonato** [comment]
What device are you using? It works for me

**Comment by rjoydip** [comment]
@lucacasonato Sorry for the incontinence. It's working now for me too after pull the latest code.
