### ISSUE TITLE
Add module owner to deno.land/x URLs

### ISSUE THREAD

**Issue by adelsz** [denoland/deno_website2#643]
Having all module names in the global namespace leads to name squatting.
This is a proposal to add package owner name to `deno.land/x` URLs:
```diff
- https://deno.land/x/MODULE_NAME@BRANCH/SCRIPT.ts
+ https://deno.land/x/OWNER/MODULE_NAME@BRANCH/SCRIPT.ts
```
It should solve some of the problems raised in:
#547, #548, #406 
I can create a PR implementing this if needed.

**Comment by alessandrorivero** [comment]
> It should solve many of the problems raised in: #547, #548, #406

It only solves the problem of name squatting. All the other problems are still there. I think to really fix all problems there needs to be something like [https://github.com/denoland/deno_website2/issues/406#issuecomment-631008536](https://github.com/denoland/deno_website2/issues/406#issuecomment-631008536)

**Comment by adelsz** [comment]
@alessandrorivero I agree, but #406 is closed now.

The whole `database.json` + PR mechanism definitely won't scale well, but might be working OK for the time being as ry mentioned.

This ticket proposes an immediate fix to name squatting and doesn't require much effort to implement.
I have changed the wording to `fix some of the problems` to avoid confusion.

**Comment by lucacasonato** [comment]
This won't be done. If you want to scope by author, just import directly from GitHub.
