### ISSUE TITLE
Kiedy będzie polska wersja strony www?

### ISSUE THREAD

**Issue by fab1an2** [denoland/deno_website2#650]
Może warto zacząć ją robić teraz zanim jeszcze nie jest tego za duzo ;)

Oczywiście chciało by się też polską dokumentacje i przewodniki

**Comment by bartlomieju** [comment]
@fab1an2 dzięki za otworzenie issue! Tłumaczenie na polski byłoby świetnym dodatkiem.
Chętnie dodamy link to tłumaczenia do oficjalnej dokumentacji, ale tłumaczenie powinno znajdować się poza oficjalnym repozytorium (https://github.com/denoland/deno/issues/5435).
 
/ 

We're more than happy to link to translations in the manual, but it should be maintained outside of this repo (https://github.com/denoland/deno/issues/5435).

**Comment by lucacasonato** [comment]
Part of #550
