### ISSUE TITLE
Markdown links on third-party modules containing images are overriden by a link to the image itself

### ISSUE THREAD

**Issue by JamesBroadberry** [denoland/deno_website2#669]
See the 'docs' badge at https://deno.land/x/bcrypt/ for an example.

The [README ](https://github.com/JamesBroadberry/deno-bcrypt/blob/master/README.md) has a link to the actual docs but gets overridden by the following code in the markdown renderer:

https://github.com/denoland/deno_website2/blob/56f9497569eb52da237e846888dc8860dcbea706/components/Markdown.tsx#L88-L90

This results in the following being rendered:
![image](https://user-images.githubusercontent.com/11461387/82554491-f2715980-9b5d-11ea-9048-a0d33237a3f0.png)

This results in the link to the image prioritised over the real link.

I'm not sure why you'd need to wrap an image in a hyperlink so an easy solution would be to remove the anchor surrounding the image. I'd be happy to submit a PR for that if there's no reason it can't be removed.

I've noticed this with badges on other third-party modules too.

**Comment by lucacasonato** [comment]
Yeah that wrapper link can be removed. If you wanna open a PR that would be great :+1:

**Comment by JamesBroadberry** [comment]
I've created the PR to remove it. I couldn't find the contribution guidelines for the website so I hope everything's alright. It seems like a pretty simple change anyway.

If there's some process I've missed, let me know and I'll sort it 👍
