### ISSUE TITLE
[Request]: Support alternative README locations on GitHub repositories.

### ISSUE THREAD

**Issue by zorbyte** [denoland/deno_website2#696]
GitHub supports the README.md file to be placed in the `.github` or `docs` folder and still be displayed on the repository landing page. It would be nice to support this on GitHub repos in deno.land/x/.

[GitHub Help Article: About Readmes](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes)

**Comment by kidonng** [comment]
Notice that you can use many other filenames (`README`, `README.txt`, `README.rst`, etc.) for README too. It's better to use [GitHub API](https://developer.github.com/v3/repos/contents/#get-the-readme) to get its content.

**Comment by lucacasonato** [comment]
> Notice that you can use many other filenames (`README`, `README.txt`, `README.rst`, etc.) for README too. It's better to use [GitHub API](https://developer.github.com/v3/repos/contents/#get-the-readme) to get its content.

I don't think we should use the API. We have a _very limited_ budget of API requests to GitHub.

**Comment by kidonng** [comment]
I know that. Basically I mean we either hard code the filenames or use the API.

**Comment by zorbyte** [comment]
Maybe an optional README location could be specified when adding packages to the database.json.
