### ISSUE TITLE
First page load of manuals often fails

### ISSUE THREAD

**Issue by gewoonwoutje** [denoland/deno_website2#719]
I often look at this screen when loading the Deno manual page after a while. 
![image](https://user-images.githubusercontent.com/9407072/82711597-25167180-9c86-11ea-879f-999d134475c7.png)

The page loads correctly after reloading.

**Comment by lucacasonato** [comment]
That is strange. Can you open the console the next time and check if there are any errors logged?

**Comment by gewoonwoutje** [comment]
Yes, I did that. Nothing to see in the console. Network logs are also empty (as they only start recording after opening dev-tools, which I only did _after_ seeing the loading screens being stuck).

Reproducing is quite impossible in the live environment. It seems very time dependent, maybe it only occurs after nobody's watched the page for an x amount of time (in which case it is a very minor bug). Maybe there is some cache or server vm sleep causing this?

**Comment by cknight** [comment]
I experience the same on occasion, and also have no errors in the console. Using latest Brave browser.

**Comment by nayeemrmn** [comment]
Same, on Chrome.

**Comment by cknight** [comment]
In case it's of help, I finally managed to reproduce with the network tab running in dev tools:
![Screenshot at 2020-05-25 22:17:09](https://user-images.githubusercontent.com/1248238/82843788-335acc80-9ed6-11ea-8ba5-93eb11687daf.png)

All files seem to have legitimate expected responses.  Console is empty.

**Comment by gewoonwoutje** [comment]
After comparing success case with failure, it seems it is missing some calls to load stuff after fetching the tags.

![image](https://user-images.githubusercontent.com/9407072/82844088-740b1380-9edf-11ea-9c6a-3a6f2e9be428.png)
![image](https://user-images.githubusercontent.com/9407072/82844095-78373100-9edf-11ea-9c9b-5aec32334f21.png)
