### ISSUE TITLE
Images does not load when viewing Third Party Modules

### ISSUE THREAD

**Issue by timharek** [denoland/deno_website2#720]
Noticed a strange thing when looking through some of the modules.

While looking at [ink](https://deno.land/x/ink), I see the images does not load or that the loading seems to be broken. Like you see in the picture below.

<img width="574" alt="Skjermbilde 2020-05-23 kl  00 30 45" src="https://user-images.githubusercontent.com/5453010/82713819-a5d86c00-9c8c-11ea-8578-1f39550a9ae8.png">

**Comment by kidonng** [comment]
This is a problem with `ink`'s README. I submitted a PR to fix it, and now the problem becomes #809 😅

**Comment by lucacasonato** [comment]
Part of #747
