### ISSUE TITLE
Html in markdown is ignored

### ISSUE THREAD

**Issue by umbopepato** [denoland/deno_website2#747]
Any HTML code in markdown is currently ignored:

https://github.com/denoland/deno_website2/blob/dbbe3783bafdcdbd3d384efebeab8fb24b3ac373/components/Markdown.tsx#L124

Many repos rely on it for aligning, sizing etc, therefore entire sections of their readmes/docs are lost on `deno.land/x/`.

Is this something you plan to support eventually?

**Comment by ry** [comment]
Happy to take a patch to support this

**Comment by lucacasonato** [comment]
Indeed - there are a lot of unsafe HTML elements. You need to filter these, which can get very complex: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb. Even things like `<img>` are unsafe if they have an `onerror` attrribute.
