### ISSUE TITLE
Support documentation and source viewing for arbitrary URLs

### ISSUE THREAD

**Issue by ry** [denoland/deno_website2#75]
https://deno.land/docs?url=https://unpkg.com/browse/lodash-es@3.10.1/chain/chain.js

This should simply reuse src/Docs.tsx

**Comment by lucacasonato** [comment]
We might want to proxy these URLs through the worker so we don't have CORS issues.

**Comment by lucacasonato** [comment]
Can be closed because doc.deno.land
