### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by Tony133** [denoland/deno_website2#758]
This link is not broken  https://github.com/denoland/deno/tree/master/website 

![screenshot](https://user-images.githubusercontent.com/11542387/82755466-f0b0cb80-9dd3-11ea-804b-d8fa09ff7f86.png)

which page should it take?

**Comment by ry** [comment]
https://github.com/denoland/deno/tree/f96aaa802b245c8b3aeb5d57b031f8a55bb07de2/website

**Comment by Tony133** [comment]
it seems that there is already a pull request https://github.com/denoland/deno_website2/pull/467, but the merge is blocked.

can you use that or do I create a new pull request?

**Comment by tokiedokie** [comment]
this issue is now solved  #893 
@ry please close this issue
