### ISSUE TITLE
Relative file paths in README are parsed incorrectly

### ISSUE THREAD

**Issue by JohanWinther** [denoland/deno_website2#765]
When you visit a third party module on https://deno.land/x/ any relative file paths in the README are incorrectly parsed as pointing to `https://deno.land/x/file.ts`, but GitHub points to the correct file.

You can see an example at https://deno.land/x/websocket_server#echo--broadcast-server, where `example_server.ts` is referenced as `[echo/broadcast server](example_server.ts)` in the README, but points to https://deno.land/x/example_server.ts when rendered on the site.

However the relative paths are working when you actually navigate to https://deno.land/x/websocket_server/README.md.

GitHub for comparison: https://github.com/JohanWinther/websocket_server#echo--broadcast-server.

**Comment by lucacasonato** [comment]
Good catch. All links in the markdown files should be relative to the canonical url of the file on `deno.land` (https://deno.land/x/websocket_server/README.md), not to the `window.location` (https://deno.land/x/websocket_server) like they are right now. I'll implement a fix for this :+1:
