### ISSUE TITLE
The Repo folders size 0B problem 

### ISSUE THREAD

**Issue by Swap76** [denoland/deno_website2#784]
<img width="1081" alt="Screenshot 2020-05-25 at 4 53 16 PM" src="https://user-images.githubusercontent.com/37082605/82809701-5a9ba480-9eaa-11ea-99d9-1234095f5946.png">

We can use the GitHub tree API to get the size fo folder but if implemented caching is must as it return the whole tree https://developer.github.com/v3/git/trees

Else we can just not show the size of the folder rather than showing 0B as in the `DirEntry interface ` the size key is option parameter 
<img width="276" alt="Screenshot 2020-05-25 at 5 08 06 PM" src="https://user-images.githubusercontent.com/37082605/82809757-730bbf00-9eaa-11ea-838a-9f4b11e2e039.png">

**Comment by kidonng** [comment]
Fixed by #796

**Comment by Swap76** [comment]
@kidonng  Thanks :-)
