### ISSUE TITLE
404 errors from date_fns JS files in registry

### ISSUE THREAD

**Issue by crabmusket** [denoland/deno_website2#79]
If you visit this page: https://deno.land/x/date_fns/addMonths/index.js you'll see a 404 error.

This reporter seemed to think it was an issue with JS files: https://github.com/denoland/registry/issues/177

However, if you look at the "repository" link on the `index.js` page linked above, you'll see it points to: https://github.com/date-fns/date-fns/tree/mastersrc/addMonths/index.js

Note `/tree/mastersrc/`, which should actually be `/tree/master/src/`. I suspect this might have something to do with the handling of the `path` parameter in database.json: https://github.com/denoland/deno_website2/blob/92a20e81c51c051080311c2edefe517049dbafcd/src/database.json#L116

Note the old registry code has a leading `/`: https://github.com/denoland/registry/blob/714ffcf29d55620fb02b53c99c7d954a366a19e7/src/database.json#L116

**Comment by crabmusket** [comment]
The `fiona` repo, which also has `"path": "src/"`, seems to have the same issue: the "repository" link at https://deno.land/x/fiona/core points to https://github.com/billymoon/fiona/tree/mastersrc/core

**Comment by lucacasonato** [comment]
All paths in the database should have a leading /. I'll PR a fix in a minute.
