### ISSUE TITLE
Relative links to images in markdown are broken

### ISSUE THREAD

**Issue by Yamboy1** [denoland/deno_website2#809]
As an example: https://deno.land/x/deno_structured_logging

The image links to `https://deno.land/x/assets/simple.png`, rather than where the actual image is `https://deno.land/x/deno_structured_logging/assets/simple.png`

After a small amount of digging, it looks to me like this commit: https://github.com/denoland/deno_website2/commit/a93f623fe3f6763ac978b87a8afb66af8524d8b0 might have caused the regression.

**Comment by Yamboy1** [comment]
As an aside, the image's alt text isn't shown next to the broken image symbol either, it would be nice if that were to be added as well

**Comment by divy-work** [comment]
+1. Facing same issue with my preview PR. 
https://deno-website2-7njek819x.now.sh/x/autopilot

**Comment by Yamboy1** [comment]
Another point I just noticed, if you go to the actual file, then this issue does not appear: https://deno.land/x/deno_structured_logging/README.md

**Comment by divy-work** [comment]
It does not work when I got to the actual file too.
https://deno.land/x/autopilot/README.md

**Comment by lucacasonato** [comment]
@divy-work For you it does not work because html in the markdown is not supported at the moment. Ref #747

@Yamboy1 I thought I had fixed that yesterday. I will investigate...

**Comment by divy-work** [comment]
@lucacasonato is there any workaround for me to use the image?

**Comment by lucacasonato** [comment]
Yes. Use markdown image syntax rather than HTML

**Comment by divy-work** [comment]
Umm yeah I'm dumb. Thanks
