### ISSUE TITLE
Manual and standard library not displaying.

### ISSUE THREAD

**Issue by KienHui** [denoland/deno_website2#814]
I'm behind a proxy that blocks raw.githubusercontent.com. This results in all the files being unfetchable, and therefore a mostly blank screen when I go to look at the manual, and "Failed to get raw file" error when I try to look at the standard library. Said proxy does not block *.github.io domains however.

**Comment by kidonng** [comment]
See #522 for a possible solution. But I would suggest you use another proxy that doesn't block `raw.githubusercontent.com` if it's possible.

**Comment by KienHui** [comment]
The proxy is a corporate one, and I don't have the pull to be able to get around it

**Comment by agar23** [comment]
I asked a similar question yesterday on the deno discord chat. Conversation can be found [here](https://discordapp.com/channels/684898665143206084/684898665151594506/715014904029118527)

I don't think this is a `deno` issue tbh. All you are trying to do here is download something from a website (in this case raw.githubusercontent.com) but your corporate network is blocking you from successfully doing that. 

IMO if your company wants to use external deno "modules" then you have two options. 

a) Have some sort of mechanism that brings in the modules into your company and the hosts them in a different subdomain (FYI this will prob require some sort of service being able to hit one of the external sites that has the deno modules)

b) Have your company just whitelist `deno.land` or GitHub (does not seem like they will allow this depending on what company it is (think security and licensing concerns))

If you do decide to explore option A look at https://github.com/denopkg/denopkg.com basically does what I'm saying but in the wild. 

Many companies use [sonatype nexus](https://www.sonatype.com/product-nexus-repository) so if they add deno support this will be much simpler.

**Comment by KienHui** [comment]
This is a `deno` website issue. There's too much stuff on raw.githubusercontent.com for proxy filter companies to categorize properly. Option A is almost certainly how deno would be used, but it can't even be properly evaluated because the manual doesn't load. Whitelisting `deno.land` would not fix the issue, as `deno.land` does in fact load, but the website makes requests to the blocked raw.githubusercontent.com to load data, instead of making requests to deno.land that are proxied by the deno website back to github.

Having the website being largely broken inhibits any potential evaluation of the software.

**Comment by lucacasonato** [comment]
Update: we don't use raw.githubusercontent.com for deno.land/x anymore. See https://deno.land/posts/registry2

**Comment by lucacasonato** [comment]
We are tracking moving manual to S3 in #1442
