### ISSUE TITLE
API Limit exceeds for star badges in third party modules

### ISSUE THREAD

**Issue by divy-work** [denoland/deno_website2#848]
The start badges that were recently added to the website requests `img.shields.io` that have a API limit:
`Exceeded limit 300 requests per 200 seconds`

So some images appear broken:
![Screenshot from 2020-05-27 12-15-22](https://user-images.githubusercontent.com/34997667/82986936-60ad9480-a014-11ea-82d4-f02225aaa6eb.png)

**Comment by Swap76** [comment]
@divy-work Can you provide the specifications of the browser as on the third-party modules page for me all badges are visible.

**Comment by lucacasonato** [comment]
@divy-work I am getting this too. I think we should revert #603 for now because of the rate limit. I see more not loaded badges than loaded badges: 
![image](https://user-images.githubusercontent.com/7829205/83007436-f7c61c80-a013-11ea-8949-7bfec63e1b53.png)
