### ISSUE TITLE
Github star indicator for Deno third party modules

### ISSUE THREAD

**Issue by uchm4n** [denoland/deno_website2#901]
It would be nice if we had some kind of indicator to identify how many Github stars every module have. This will help lot of users to pick popular modules and encourages module developers to do better products. Otherwise module list is getting messy and it's not clear what is worth to look into. 
Everybody just trying out Deno and every "hello world" module is in there.
Maybe later we could add filters too?

Something like this:
![stars](https://user-images.githubusercontent.com/1173405/83201013-99339800-a112-11ea-879d-6124e30fcd98.png)

**Comment by lucacasonato** [comment]
Ref #464. This was implemented a few days ago, but it had to be reverted because of API rate limit issues.

Anyway I am in favor once we figure out the rate limit issues, and having a `Sort by star #` option would be awesome.

**Comment by uchm4n** [comment]
Numbers can be cached, so each module will get updated each 1 day or so and displayed afterwards. With little logic, if star number > 300 gets more frequent cache update. Just saying
If there is not concret solution, than I'll close this issue
