### ISSUE TITLE
Incorrect / invalid titles in the OG tags for /x/ modules

### ISSUE THREAD

**Issue by JipFr** [denoland/deno_website2#910]
Third-party module pages such as https://deno.land/x/talk_lib/ returns an incorrect value in its `title` and `og:title` properties. For some reason it's also different locally. When looking at the network request for https://deno.land/x/talk_lib/, you see 
```HTML
<meta name="title" content="deno.land/x/undefined" />
```
and 
```HTML
<meta property="og:title" content="deno.land/x/undefined" />
```

And yet, when you look at the head in the devtools it's different again, most likely altered by the JS on the page. In the devtools it says 
```HTML
<meta name="title" content="deno.land/x/talk_libundefined">
<meta property="og:title" content="deno.land/x/talk_libundefined">
```

**Comment by kennanseno** [comment]
Looking at this now
