### ISSUE TITLE
Discord invitation link seems expired

### ISSUE THREAD

**Issue by rewebcan** [denoland/deno_website2#938]
I was trying to join discord server to ask some question about developing new packages, but it seems url is not valid.

**Comment by nayeemrmn** [comment]
What link are you using, and where on the site did you find it?

**Comment by koji** [comment]
@rewebcan you can try this https://discord.gg/TGMHGv6
However, https://discord.gg/deno that is used currently works for me.

**Comment by lucacasonato** [comment]
I can't find this link and there has been no response since may 30th so I am gonna close this.
