### ISSUE TITLE
Add a link to GitHub when rate limited

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno_website2#946]
In the deno discord I saw a new user ask for help regarding std API because they were no longer able to view documentation. They didn't know that they could still view it if they look at the repository directly on GitHub instead of through the deno website.

I think we should include a link to the page on GitHub when a user encounters GitHub API rate limiting. I believe the same should apply for third party modules.

Below is a screenshot of the error.
<img width="840" alt="Annotation 2020-05-30 172326" src="https://user-images.githubusercontent.com/3241653/83340255-7e405f80-a29b-11ea-8e2d-327aa00607d2.png">

**Comment by kidonng** [comment]
#433

**Comment by ry** [comment]
This was fixed in https://github.com/denoland/deno_website2/pull/1403. Read more about it at https://deno.land/posts/registry2
