### ISSUE TITLE
I'd like to convert cli-tables to deno

### ISSUE THREAD

**Issue by ninjaa** [denoland/deno_website2#949]
I'd like to convert cli-tables to deno https://github.com/Automattic/cli-table

Can someone with more experience please give me guidelines on how to do this? 

I'd ultimately like to be able to eg import cli-table from `https://github.com/ninjaa/deno-cli-table`

let me know please. I couldn't figure out where to put this request and it said for new packages open a GH issue so ... hope it's the right place. Lmk if there's a slack or irc or something.

**Comment by kennanseno** [comment]
@ninjaa there's a discord group you can use for this.

https://discord.gg/A2sUjR

**Comment by rjoydip** [comment]
@ninjaa Use [https://deno.land/x/ascii_table](https://deno.land/x/ascii_table)
It's equivalent to `cli-table`

**Comment by lucacasonato** [comment]
This issue tracker is for issues and feature requests regarding the deno.land website. Questions about Deno should be asked on Discord: https://discord.gg/deno
